"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { Icon } from "@/components/Icon";
import { decideRecommendation,getRecommendations } from "@/lib/api";

const text=(v:unknown,fallback="Not provided")=>typeof v==="string"&&v?v:fallback;
const pct=(v:unknown)=>v==null?"Unavailable":`${(Number(v)*100).toFixed(1)}%`;

export default function RecommendationsPage(){
  const [rows,setRows]=useState<Array<Record<string,unknown>>>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [filter,setFilter]=useState("active");
  useEffect(()=>{void getRecommendations().then(setRows).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))},[]);
  async function dismiss(id:string){try{await decideRecommendation(id,"dismissed");setRows(r=>r.map(x=>String(x.id)===id?{...x,status:"dismissed"}:x))}catch(e){setError(e instanceof Error?e.message:"Could not dismiss recommendation")}}
  const visible=rows.filter(r=>filter==="all"||["open","active"].includes(String(r.status??"open")));
  return <div className="page-wrap"><header className="page-heading"><div><p className="eyebrow">Decision support</p><h1 className="page-title">Recommendations</h1><p className="page-subtitle">Investment decision memos with a visible trigger, expected effect, trade-offs, evidence and mandate relevance.</p></div><div className="segmented"><button className="segment" aria-selected={filter==="active"} onClick={()=>setFilter("active")}>Active</button><button className="segment" aria-selected={filter==="all"} onClick={()=>setFilter("all")}>All</button></div></header>{error?<div className="notice notice-error mb-4" role="alert"><Icon name="warning"/>{error}</div>:null}{loading?<div className="panel h-72 skeleton"/>:visible.length?<div className="grid gap-4">{visible.map((r,i)=>{
    const evidence=(r.evidence&&typeof r.evidence==="object"?r.evidence:{}) as Record<string,unknown>;const expected=(r.expected_effect&&typeof r.expected_effect==="object"?r.expected_effect:{}) as Record<string,unknown>;const id=String(r.id??i),portfolioId=String(r.portfolio_id??"");const priority=text(r.priority??r.severity,"");const high=["critical","high"].includes(priority.toLowerCase());
    const classification=text(evidence.classification,"monitoring_warning");const mandate=classification==="mandate_breach"?`Breaches confirmed IPS limit ${pct(evidence.related_ips_limit)}.`:evidence.related_ips_limit!=null?`Monitoring threshold is separate from the ${pct(evidence.related_ips_limit)} IPS limit; this is not a mandate breach.`:"No related IPS limit was available.";
    return <article className={`panel ${high?"border-l-[3px] border-l-[#b9473c]":""}`} key={id}><div className="p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2"><span className={`badge ${high?"badge-bad":"badge-warn"}`}>{priority||text(r.status,"open")}</span><span className="badge">{text(r.trigger_label,"Portfolio signal")}</span></div><span className="text-[11px] text-muted">{typeof r.freshness==="object"?Object.values(r.freshness as Record<string,unknown>).map(String).join(" · "):"Freshness unavailable"}</span></div><h2 className="mt-4 max-w-4xl text-[17px] font-semibold leading-6 tracking-[-.015em]">{text(r.message,"Recommendation details unavailable")}</h2><div className="mt-5 grid gap-5 border-t border-line pt-5 sm:grid-cols-4"><Cell label="Trigger" value={`${text(evidence.rule_type,"Portfolio signal")} · threshold ${pct((evidence.rule_threshold as Record<string,unknown>|undefined)?.maximum)} · current ${pct(evidence.current_value)}`}/><Cell label="Mandate relevance" value={mandate}/><Cell label="Expected effect" value={text(expected.reason??expected.note,"No allocation or trade effect is inferred automatically.")}/><Cell label="Uncertainty" value={typeof r.uncertainty==="object"?text((r.uncertainty as Record<string,unknown>).note,"Review freshness and evidence before acting."):"Review freshness and evidence before acting."}/></div></div><div className="flex flex-wrap items-center justify-end gap-2 bg-[#fafaf8] px-5 py-3">{portfolioId?<><Link className="btn btn-secondary" href={`/portfolios/${portfolioId}/risk` as never}>Open risk</Link><Link className="btn btn-primary" href={`/portfolios/${portfolioId}/build` as never}>Review in Build</Link></>:<span className="text-[11px] text-muted">Portfolio unavailable</span>}<button className="btn btn-quiet" onClick={()=>dismiss(id)}>Dismiss</button></div></article>})}</div>:<Empty/>}</div>;
}

function Cell({label,value}:{label:string;value:string}){return <div><p className="metric-label">{label}</p><p className="mt-2 text-[12px] leading-5 text-[#3f454b]">{value}</p></div>}
function Empty(){return <div className="rounded-xl bg-surface py-14 text-center"><Icon name="check" size={28} className="mx-auto text-accent"/><strong className="mt-3 block text-[13px]">No active recommendations</strong><span className="mt-1 block text-[12px] text-muted">Grounded decision-support items will appear when analysis raises a signal.</span></div>}
