"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {archivePortfolio,clearApiCache,comparePortfolios,createPortfolio,duplicatePortfolio,getPortfolioRiskFlags,getPortfolioSummary,getPortfolios,selectDefaultPortfolio,type Portfolio,type PortfolioSummary} from "@/lib/api";
import {WorkspaceHeader} from "@/components/WorkspaceHeader";
import {formatDate,formatNumber,formatPercent,humanize} from "@/lib/overview";
import {Icon} from "@/components/Icon";
import styles from "./management.module.css";
type Row={portfolio:Portfolio;summary:PortfolioSummary|null;riskCount:number|null;errors:string[]};
export function PortfolioManagement(){
 const router=useRouter();const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[view,setView]=useState("active"),[query,setQuery]=useState(""),[selected,setSelected]=useState(""),[creating,setCreating]=useState(false),[name,setName]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[archiveId,setArchiveId]=useState(""),[checked,setChecked]=useState<string[]>([]),[comparison,setComparison]=useState<PortfolioSummary[]>([]);
 async function load(){const portfolios=await getPortfolios();const enriched=await Promise.all(portfolios.map(async portfolio=>{const [summary,risk]=await Promise.allSettled([getPortfolioSummary(portfolio.id),getPortfolioRiskFlags(portfolio.id)]);return {portfolio,summary:summary.status==="fulfilled"?summary.value:null,riskCount:risk.status==="fulfilled"?risk.value.flags.length:null,errors:[summary.status==="rejected"?"Valuation unavailable":"",risk.status==="rejected"?"Risk coverage unavailable":""].filter(Boolean)}}));setRows(enriched)}
 useEffect(()=>{if(new URLSearchParams(window.location.search).get("create")==="1")setCreating(true);void load().catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[]);
 const visible=rows.filter(row=>(view==="archived"?!!row.portfolio.archived_at:!row.portfolio.archived_at)&&row.portfolio.name.toLowerCase().includes(query.toLowerCase())),detail=visible.find(row=>row.portfolio.id===selected)??visible[0];
 const announce=()=>{clearApiCache();window.dispatchEvent(new Event("psx-portfolio-change"))};
 async function action(fn:()=>Promise<unknown>,success:string){setBusy(true);setError("");try{await fn();announce();await load();setMessage(success);setArchiveId("")}catch(reason){setError(reason instanceof Error?reason.message:"Portfolio update failed")}finally{setBusy(false)}}
 async function create(event:FormEvent){event.preventDefault();if(!name.trim())return;setBusy(true);setError("");try{const portfolio=await createPortfolio(name.trim());announce();router.push(`/portfolios/${portfolio.id}/ips`)}catch(reason){setError(reason instanceof Error?reason.message:"Could not create portfolio");setBusy(false)}}
 async function compare(){setBusy(true);setError("");try{setComparison((await comparePortfolios(checked)).portfolios)}catch(reason){setError(reason instanceof Error?reason.message:"Comparison unavailable")}finally{setBusy(false)}}
 return <div className={styles.page}><WorkspaceHeader title=""><nav className="workspace-header-tabs" aria-label="Portfolio management view">{["active","archived"].map(value=><button key={value} aria-current={view===value?"page":undefined} onClick={()=>{setView(value);setArchiveId("")}}>{value==="active"?"Your portfolios":"Archived"}</button>)}</nav><button className="workspace-header-action" onClick={()=>{setCreating(true);setMessage("")}}><Icon name="plus" size={15}/> New portfolio</button></WorkspaceHeader>
  <div className={styles.content}><div className={styles.toolbar}><input aria-label="Filter portfolios" placeholder="Filter portfolios" value={query} onChange={event=>setQuery(event.target.value)}/><span>{visible.length} {view} portfolios</span>{checked.length>=2?<button disabled={busy} onClick={()=>void compare()}>Compare {checked.length}</button>:null}</div>
  {error?<p className={styles.error} role="alert">{error}</p>:null}{message?<p className={styles.note} role="status">{message}</p>:null}
  {creating?<form className={styles.create} onSubmit={event=>void create(event)}><div><h2>New portfolio</h2><p>A separate holdings ledger and investment mandate.</p></div><label>Portfolio name<input autoFocus required maxLength={120} value={name} onChange={event=>setName(event.target.value)} placeholder="e.g. Long-term investments"/></label><div><button disabled={busy||!name.trim()}>{busy?"Creating…":"Create and define IPS"}</button><button type="button" onClick={()=>setCreating(false)}>Cancel</button></div></form>:null}
  {comparison.length?<section className={styles.comparison}><div><h2>Portfolio comparison</h2><button aria-label="Close portfolio comparison" onClick={()=>setComparison([])}>×</button></div><div className={styles.tableScroll}><table><thead><tr><th>Portfolio</th><th>Stored value</th><th>Unrealized PnL</th><th>Day change</th><th>Prices as of</th></tr></thead><tbody>{comparison.map(row=><tr key={row.portfolio.id}><td>{row.portfolio.name}</td><td>{row.portfolio.base_currency} {formatNumber(row.total_value)}</td><td>{formatPercent(row.unrealized_gain_loss_percent)}</td><td>{formatPercent(row.day_change_percent)}</td><td>{formatDate(row.data_freshness_date)}{!row.valuation_complete?" · Partial":""}</td></tr>)}</tbody></table></div></section>:null}
  {loading?<p className={styles.empty} role="status">Loading stored portfolios…</p>:visible.length?<div className={styles.tableScroll}><table><thead><tr><th aria-label="Compare selection"/><th>Portfolio</th><th>Value</th><th>Day change</th><th>Holdings</th><th>Risk coverage</th><th>Prices as of</th></tr></thead><tbody>{visible.map(row=><tr key={row.portfolio.id} aria-selected={detail?.portfolio.id===row.portfolio.id}><td><input type="checkbox" aria-label={`Compare ${row.portfolio.name}`} checked={checked.includes(row.portfolio.id)} onChange={event=>setChecked(old=>event.target.checked?[...old,row.portfolio.id]:old.filter(id=>id!==row.portfolio.id))}/></td><td><button className={styles.name} onClick={()=>{setSelected(row.portfolio.id);setArchiveId("")}}>{row.portfolio.name}</button><small>{row.portfolio.is_default?"Selected portfolio · ":""}{humanize(row.portfolio.source_mode)}</small></td><td>{row.summary?`${row.portfolio.base_currency} ${formatNumber(row.summary.total_value,0)}`:"—"}{row.summary&&!row.summary.valuation_complete?<small>Partial valuation</small>:null}</td><td>{formatPercent(row.summary?.day_change_percent)}</td><td>{row.summary?.holdings.length??"—"}</td><td>{row.riskCount==null?"Unavailable":row.riskCount?`${row.riskCount} flags`:"No returned flags"}</td><td>{formatDate(row.summary?.data_freshness_date)}</td></tr>)}</tbody></table></div>:<div className={styles.empty}><h2>{query?"No portfolios match":"No portfolios in this view"}</h2><p>{query?"Try another portfolio name.":"Create a portfolio to keep its holdings and mandate together."}</p><button onClick={()=>setCreating(true)}>New portfolio</button></div>}
  </div><aside className={styles.detail} aria-label="Portfolio management detail">{detail?<><h2>{detail.portfolio.name}</h2><p>{detail.portfolio.goal_summary??"Investment mandate not recorded."}</p><dl><div><dt>Base currency</dt><dd>{detail.portfolio.base_currency}</dd></div><div><dt>Source</dt><dd>{humanize(detail.portfolio.source_mode)}</dd></div><div><dt>History</dt><dd>{detail.portfolio.history_complete?"Complete ledger":"Opening balance"}</dd></div><div><dt>IPS</dt><dd>{detail.portfolio.selected_ips_version_id?"Recorded":"Needs definition"}</dd></div><div><dt>Unrealized PnL</dt><dd>{formatPercent(detail.summary?.unrealized_gain_loss_percent)}</dd></div></dl>{detail.errors.map(value=><p className={styles.note} key={value}>{value}</p>)}{detail.summary?.valuation_note?<p className={styles.note}>{detail.summary.valuation_note}</p>:null}<section><h3>Manage this portfolio</h3><Link href={`/portfolios/${detail.portfolio.id}/overview`}>Open portfolio <span>↗</span></Link><Link href={`/portfolios/${detail.portfolio.id}/ips`}>Review investment mandate <span>›</span></Link>{!detail.portfolio.archived_at&&!detail.portfolio.is_default?<button disabled={busy} onClick={()=>void action(()=>selectDefaultPortfolio(detail.portfolio.id),"Selected portfolio updated.")}>Use as selected portfolio</button>:null}<button disabled={busy} onClick={()=>void action(()=>duplicatePortfolio(detail.portfolio.id,`${detail.portfolio.name} copy`),"Copied portfolio and current positions.")}>Duplicate with current positions</button>{!detail.portfolio.archived_at?<button disabled={busy} onClick={()=>setArchiveId(detail.portfolio.id)}>Archive portfolio</button>:null}</section>{archiveId===detail.portfolio.id?<div className={styles.archive} role="group" aria-label="Confirm portfolio archive"><p>Archive {detail.portfolio.name}? Its stored records will remain in the archived view.</p><button disabled={busy} onClick={()=>void action(()=>archivePortfolio(archiveId),"Portfolio archived.")}>Confirm archive</button><button onClick={()=>setArchiveId("")}>Cancel</button></div>:null}<p className={styles.note}>Values use stored holdings and dated market prices. Missing valuations and risk coverage remain unavailable.</p></>:<p className={styles.note}>Select a portfolio to inspect its mandate, source, and available actions.</p>}</aside>
 </div>;
}
