"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Icon } from "@/components/Icon";
import { Portfolio,PortfolioRiskFlag,PortfolioSummary,archivePortfolio,comparePortfolios,createPortfolio,duplicatePortfolio,getPortfolioRiskFlags,getPortfolioSummary,getPortfolios } from "@/lib/api";

type Row={portfolio:Portfolio;summary?:PortfolioSummary;flags:PortfolioRiskFlag[]};
const money=(v:unknown)=>`PKR ${new Intl.NumberFormat("en-PK",{notation:"compact",maximumFractionDigits:2}).format(Number(v||0))}`;
const pct=(v:unknown)=>v==null?"—":`${Number(v)>0?"+":""}${Number(v).toFixed(2)}%`;

export default function PortfoliosPage(){
  const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [showCreate,setShowCreate]=useState(false);const [compare,setCompare]=useState<string[]>([]);const [comparison,setComparison]=useState<PortfolioSummary[]>([]);
  async function load(){const portfolios=await getPortfolios();const enriched=await Promise.all(portfolios.map(async portfolio=>{const [summary,risk]=await Promise.all([getPortfolioSummary(portfolio.id).catch(()=>undefined),getPortfolioRiskFlags(portfolio.id).catch(()=>({flags:[]}))]);return{portfolio,summary,flags:risk.flags}}));setRows(enriched)}
  useEffect(()=>{void load().catch((e:Error)=>setMessage(e.message)).finally(()=>setLoading(false))},[]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const name=String(new FormData(e.currentTarget).get("name"));try{await createPortfolio(name);setShowCreate(false);setMessage("Portfolio created.");await load()}catch(err){setMessage(err instanceof Error?err.message:"Could not create portfolio")}}
  async function duplicate(row:Row){try{await duplicatePortfolio(row.portfolio.id,`${row.portfolio.name} copy`);setMessage("Portfolio duplicated with its current positions.");await load()}catch(err){setMessage(err instanceof Error?err.message:"Could not duplicate portfolio")}}
  async function archive(row:Row){try{await archivePortfolio(row.portfolio.id);setMessage("Portfolio archived.");await load()}catch(err){setMessage(err instanceof Error?err.message:"Could not archive portfolio")}}
  async function runCompare(){try{setComparison((await comparePortfolios(compare)).portfolios)}catch(err){setMessage(err instanceof Error?err.message:"Could not compare portfolios")}}
  return <div className="page-wrap">
    <header className="page-heading"><div><p className="eyebrow">Portfolio management</p><h1 className="page-title">Portfolios</h1><p className="page-subtitle">Separate mandates, performance histories, risk limits and decision records.</p></div><div className="flex gap-2">{compare.length>=2?<button className="btn btn-secondary" onClick={runCompare}>Compare {compare.length}</button>:null}<button className="btn btn-primary" onClick={()=>setShowCreate(true)}><Icon name="plus"/>Create portfolio</button></div></header>
    {message?<div className="notice mb-4"><span>{message}</span></div>:null}
    {showCreate?<form onSubmit={create} className="panel mb-4 flex flex-wrap items-end gap-3 p-4"><label className="field-label min-w-[240px] flex-1">Portfolio name<input className="field" autoFocus name="name" placeholder="e.g. Retirement mandate" required/></label><button className="btn btn-primary">Create portfolio</button><button type="button" className="btn btn-secondary" onClick={()=>setShowCreate(false)}>Cancel</button></form>:null}
    {comparison.length?<section className="panel mb-4"><div className="panel-head"><h2 className="panel-title">Portfolio comparison</h2><button className="icon-btn" aria-label="Close comparison" onClick={()=>setComparison([])}><Icon name="close"/></button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Portfolio</th><th>Value</th><th>Total return</th><th>Day change</th><th>Holdings</th><th>Freshness</th></tr></thead><tbody>{comparison.map(s=><tr key={s.portfolio.id}><td className="font-bold">{s.portfolio.name}</td><td>{money(s.total_value)}</td><td className={Number(s.unrealized_gain_loss_percent)>=0?"positive":"negative"}>{pct(s.unrealized_gain_loss_percent)}</td><td className={Number(s.day_change_percent)>=0?"positive":"negative"}>{pct(s.day_change_percent)}</td><td>{s.holdings.length}</td><td>{s.data_freshness_date??"—"}</td></tr>)}</tbody></table></div></section>:null}
    <div className="grid gap-3 xl:grid-cols-2">
      {loading?[1,2,3].map(i=><div className="panel h-56 p-5" key={i}><div className="skeleton h-6 w-1/3"/><div className="skeleton mt-8 h-20 w-full"/></div>):rows.map(row=><article key={row.portfolio.id} className="panel">
        <div className="flex items-start justify-between gap-3 border-b border-line p-4"><div className="flex gap-3"><input aria-label={`Select ${row.portfolio.name} for comparison`} type="checkbox" checked={compare.includes(row.portfolio.id)} onChange={e=>setCompare(c=>e.target.checked?[...c,row.portfolio.id]:c.filter(id=>id!==row.portfolio.id))}/><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-[15px] font-bold">{row.portfolio.name}</h2>{row.portfolio.is_default?<span className="badge badge-good">Default</span>:null}{row.portfolio.archived_at?<span className="badge">Archived</span>:null}</div><p className="mt-1 text-[11px] text-muted">{row.portfolio.goal_summary||"Goal not defined"}</p></div></div><div className="flex"><button className="icon-btn" title="Duplicate" aria-label={`Duplicate ${row.portfolio.name}`} onClick={()=>duplicate(row)}><Icon name="document"/></button><button className="icon-btn" title="Archive" aria-label={`Archive ${row.portfolio.name}`} onClick={()=>archive(row)}><Icon name="more"/></button></div></div>
        <Link href={`/portfolios/${row.portfolio.id}/overview`} className="block p-4 hover:bg-[#f8fafb]"><div className="grid grid-cols-2 gap-x-5 gap-y-4 sm:grid-cols-4"><Metric label="Value" value={row.summary?money(row.summary.total_value):"—"}/><Metric label="Total return" value={pct(row.summary?.unrealized_gain_loss_percent)} tone={Number(row.summary?.unrealized_gain_loss_percent)>=0?"positive":"negative"}/><Metric label="Risk status" value={row.flags.length?`${row.flags.length} flag${row.flags.length===1?"":"s"}`:"Clear"} tone={row.flags.length?"negative":"positive"}/><Metric label="Goal progress" value={row.portfolio.selected_ips_version_id?"Tracked":"Not set"}/></div><div className="mt-4 flex items-center justify-between border-t border-line pt-3"><span className="text-[11px] text-muted">{row.portfolio.history_complete?"Complete ledger history":"Opening-balance history"} · {row.portfolio.source_mode}</span><span className="flex items-center gap-1 text-xs font-bold text-[#244e70]">Open workspace <Icon name="chevron" size={14}/></span></div></Link>
      </article>)}
    </div>
    {!loading&&!rows.length?<div className="panel empty-state"><Icon name="briefcase" size={28}/><strong>No portfolios yet</strong><span>Create a portfolio to begin tracking holdings and mandate progress.</span><button className="btn btn-primary mt-2" onClick={()=>setShowCreate(true)}>Create portfolio</button></div>:null}
  </div>;
}
function Metric({label,value,tone=""}:{label:string;value:string;tone?:string}){return <div><p className="metric-label">{label}</p><p className={`data-font mt-1 text-base font-semibold ${tone}`}>{value}</p></div>}
