import { describe, expect, it } from "vitest";
import type { IpsVersion } from "@/lib/api";
import { blankIps, fromIps, ipsPayload } from "./ipsForm";
const version = {id:"ips-owned",version:2,status:"confirmed",constraints:{min_cash_weight:.1,max_sector_weight:.4,target_volatility:.18,target_beta:1,long_only:true,risk_budgets:{ABC:.5,XYZ:.5},allowed_currencies:["PKR"],risk_capacity:"moderate",risk_willingness:"low",overall_risk_tolerance:"low",objective_inputs:{starting_capital:100000,target_value:200000,horizon_years:7,annual_contribution:0},required_return_method:{valuation_date:"2025-01-01",target_date:"2032-01-01",target_value_is_real:true,inflation_rate:.05,dated_contributions:[{date:"2026-01-01",amount:1000}]}}} as unknown as IpsVersion;
describe("IPS immutable version payload",()=>{
 it("leaves absent mandate facts blank instead of assigning fabricated preferences",()=>{expect(fromIps()).toEqual(blankIps);expect(fromIps(version).benchmark).toBe("");expect(fromIps(version).maxWeight).toBe("")});
 it("retains configured risk budgets, exclusions and dated real-goal basis when editing a visible constraint",()=>{const form=fromIps(version);form.maxSector="35";const payload=ipsPayload(form,version);expect(payload.constraints).toMatchObject({risk_budgets:{ABC:.5,XYZ:.5},allowed_currencies:["PKR"],max_sector_weight:.35,target_volatility:.18});expect(payload).toMatchObject({target_value_is_real:true,inflation_rate:.05,dated_contributions:[{contribution_date:"2026-01-01",amount:1000}],valuation_date:"2025-01-01",target_date:"2032-01-01"})});
 it("lets a changed horizon replace the old fixed target date",()=>{const form=fromIps(version);form.years="8";expect(ipsPayload(form,version).target_date).toBeNull();expect(ipsPayload(form,version).horizon_years).toBe(8)});
 it("removes deliberately cleared constraints and does not silently convert missing limits to zero",()=>{const form=fromIps(version);form.minCash="";form.proxy="";const constraints=ipsPayload(form,version).constraints as Record<string,unknown>;expect(constraints).not.toHaveProperty("min_cash_weight");expect(constraints).not.toHaveProperty("max_instrument_weight");expect(constraints.risk_budgets).toEqual({ABC:.5,XYZ:.5})});
});
