"use client";
import { useEffect, useState, type FormEvent } from "react";
import { useParams } from "next/navigation";
import { PortfolioWorkspace } from "@/components/PortfolioWorkspace";
import { useWorkspaceData } from "@/components/workspace/useWorkspaceData";
import { clearApiCache, createIpsVersion, getIpsCompliance, getIpsVersions, type IpsVersion, type Compliance } from "@/lib/api";
import { fromIps, ipsPayload, type IpsForm, blankIps } from "./ipsForm";
import { formatDate, humanize } from "@/lib/overview";
import styles from "./ips.module.css";
export function IpsWorkspace() {
 const {portfolioId}=useParams<{portfolioId:string}>();
 const {data,failures}=useWorkspaceData(portfolioId,"ips");
 const [updated,setUpdated]=useState<IpsVersion[]|null>(null),[compliance,setCompliance]=useState<Compliance|null>(null);
 const versions=updated ?? data.ips;
 const confirmed=versions.filter(row=>row.status==="confirmed").sort((a,b)=>b.version-a.version)[0];
 const [form,setForm]=useState<IpsForm>(blankIps),[base,setBase]=useState<IpsForm>(blankIps),[review,setReview]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const next=fromIps(confirmed);setForm(next);setBase(next);setReview(false)},[confirmed?.id]);
 useEffect(()=>{setUpdated(null);setCompliance(null)},[portfolioId]);
 const changes=(Object.keys(form) as Array<keyof IpsForm>).filter(key=>form[key]!==base[key]);
 const current=compliance ?? data.compliance;
 const status=current?.status ?? (current ? current.compliant ? "PASS" : "BREACH" : "NOT_EVALUATED");
 const change=(key:keyof IpsForm,value:string)=>{setForm(current=>({...current,[key]:value}));setReview(false)};
 async function submit(event:FormEvent){event.preventDefault();setMessage("");const order:Record<string,number>={low:0,moderate:1,high:2};if(form.capacity && form.willingness && form.overall && order[form.overall]>Math.min(order[form.capacity],order[form.willingness])){setMessage("Overall risk tolerance cannot exceed capacity or willingness.");return}if(!review){setReview(true);return}setSaving(true);try{await createIpsVersion(portfolioId,ipsPayload(form,confirmed),true);clearApiCache();setUpdated(await getIpsVersions(portfolioId));setCompliance(await getIpsCompliance(portfolioId).catch(()=>null));setMessage("New IPS version confirmed. The previous version remains in the audit record.");setReview(false)}catch(error){setMessage(error instanceof Error ? error.message : "IPS confirmation failed.")}finally{setSaving(false)}}
 const field=(key:keyof IpsForm,label:string,type="number")=><label key={key}>{label}<input type={type} value={form[key]} step="any" min={type==="number" ? "0" : undefined} placeholder="Not configured" onChange={event=>change(key,event.target.value)}/></label>;
 const risk=(key:keyof IpsForm,label:string)=><label key={key}>{label}<select value={form[key]} onChange={event=>change(key,event.target.value)}><option value="">Not configured</option>{["low","moderate","high"].map(value=><option key={value} value={value}>{humanize(value)}</option>)}</select></label>;
 const flag=(key:keyof IpsForm,label:string)=><label key={key}>{label}<select value={form[key]} onChange={event=>change(key,event.target.value)}><option value="">Not configured</option><option value="true">On</option><option value="false">Off</option></select></label>;
 return <PortfolioWorkspace portfolioId={portfolioId} active="settings"><div className={styles.layout}>
 <aside data-workspace-left-panel className={styles.nav}><a href="#ips-goals" className={styles.selected}>Confirmed IPS {confirmed ? `v${confirmed.version}` : "unavailable"}</a><button onClick={()=>document.getElementById("ips-goals")?.scrollIntoView()}>Draft changes {changes.length ? `(${changes.length})` : ""}</button><nav aria-label="Investment policy sections">{[["goals","Objectives"],["risk","Risk capacity"],["liquidity","Liquidity"],["constraints","Constraints"],["benchmarks","Benchmarks"],["history","Audit record"]].map(([id,label])=><a key={id} href={`#ips-${id}`}>{label}</a>)}</nav></aside>
 <form data-portfolio-panel="content" className={styles.main} onSubmit={submit}><h1>Investment policy</h1><p className={styles.subtitle}>Your portfolio’s confirmed investment policy statement. Changes create a new version after review and confirmation.</p>{failures.length ? <p className={styles.notice} role="alert">{failures.join(" · ")}</p> : null}{message ? <p className={styles.notice} role="status">{message}</p> : null}
 <section id="ips-goals"><h2>Goals</h2><div className={styles.fields}>{field("goal","Primary goal","text")}{field("years","Investment horizon (years)")}<label>Required return (annual)<output>{confirmed?.required_return == null ? "Unavailable" : `${(Number(confirmed.required_return)*100).toFixed(2)}%`}</output></label>{field("capital","Starting capital (PKR)")}{field("target","Target value (PKR)")}{field("contribution","Annual contribution (PKR)")}</div><p className={styles.note}>Required return comes from the confirmed goal calculation. Draft goal changes are calculated by the server after confirmation.</p></section>
 <section id="ips-risk"><h2>Risk capacity</h2><div className={styles.fields}>{risk("capacity","Risk capacity")}{risk("willingness","Risk willingness")}{risk("overall","Overall tolerance")}</div></section>
 <section id="ips-liquidity"><h2>Liquidity</h2><div className={styles.fields}>{field("liquidity","Near-term requirement (PKR)")}{field("minCash","Minimum cash allocation (%)")}</div></section>
 <section id="ips-constraints"><h2>Constraints</h2><div className={styles.fields}>{field("maxWeight","Maximum single position (%)")}{field("maxSector","Maximum sector allocation (%)")}{field("volatility","Volatility ceiling (annual %) ")}{field("beta","Beta ceiling (vs proxy)")}{flag("longOnly","Long only")}{flag("shariah","Shariah only")}</div></section>
 <section id="ips-benchmarks"><h2>Benchmarks</h2><div className={styles.fields}>{field("benchmark","Performance benchmark","text")}{field("proxy","CAPM proxy","text")}{field("riskFree","Risk-free series key","text")}</div><p className={styles.note}>A configured series key requires observed data before risk-free-dependent analysis becomes available.</p></section>
 {review ? <section aria-label="Review mandate changes"><h2>Review changes</h2><div className={styles.tableWrap}><table><thead><tr><th>Field</th><th>Confirmed</th><th>Draft</th></tr></thead><tbody>{changes.map(key=><tr key={key}><td>{humanize(key)}</td><td>{base[key] || "Not configured"}</td><td>{form[key] || "Not configured"}</td></tr>)}</tbody></table></div>{!changes.length ? <p>No changes to confirm.</p> : null}</section> : null}
 <div className={styles.actions}><button className={styles.primary} disabled={saving || (!changes.length && Boolean(confirmed))}>{saving ? "Confirming…" : review ? "Confirm new version" : "Review changes"}</button><button type="button" onClick={()=>{setForm({...base});setReview(false)}}>Discard draft</button></div>
 <section id="ips-history"><h2>Version history</h2><div className={styles.tableWrap}><table><thead><tr><th>Version</th><th>Status</th><th>Confirmed</th><th>Required return</th></tr></thead><tbody>{versions.map(row=><tr key={row.id}><td>v{row.version}</td><td>{row.status}</td><td>{formatDate(row.confirmed_at)}</td><td>{row.required_return == null ? "—" : `${(Number(row.required_return)*100).toFixed(2)}%`}</td></tr>)}</tbody></table></div>{!versions.length ? <p className={styles.note}>No IPS versions available.</p> : null}</section></form>
 <aside data-portfolio-panel="context" className={styles.rail}><section><h2>Mandate review</h2><p>Only confirmed investment preferences govern this portfolio.</p></section><section><h3>Current compliance</h3><p className={styles.notice}>{status==="PASS" ? "Within mandate" : status==="BREACH" ? `${current?.violations.length ?? 0} mandate issues` : "Unavailable / not fully evaluated"}</p>{current?.not_evaluated?.filter(row=>row.severity==="availability").map((row,index)=><p className={styles.note} key={index}>{String(row.message ?? "Analytical input missing")}</p>)}</section><section><h3>Binding constraints</h3>{([["minCash","Minimum cash allocation","%"],["maxWeight","Maximum single position","%"],["maxSector","Maximum sector allocation","%"],["volatility","Volatility ceiling","%"],["beta","Beta ceiling",""],["longOnly","Long only",""]] as const).map(([key,label,unit])=><div className={styles.binding} key={key}><span>{label}</span><strong>{base[key] ? key==="longOnly" ? base[key]==="true" ? "On" : "Off" : `${base[key]}${unit}` : "Unavailable"}</strong></div>)}</section><section><h3>Analytical inputs</h3><div className={styles.binding}><span>CAPM proxy</span><strong>{base.proxy || "Not configured"}</strong></div><div className={styles.binding}><span>Risk-free series</span><strong>{base.riskFree || "Not configured"}</strong></div><p className={styles.note}>Observed input availability is reported in Quant. Configuration alone does not establish coverage.</p></section></aside>
 </div></PortfolioWorkspace>;
}
