"use client";
import { useParams } from "next/navigation";import { useEffect,useMemo,useState } from "react";import Link from "next/link";
import { Icon } from "@/components/Icon";import { LineChart } from "@/components/WorkstationChart";import { CompanyDetail,MarketPrice,PortfolioSummary,getCompanyDetail,getCompanyHistory,getPortfolioSummary,getPortfolios } from "@/lib/api";
const num=(v:unknown,d=2)=>new Intl.NumberFormat("en-PK",{maximumFractionDigits:d}).format(Number(v||0));const pct=(v:unknown)=>v==null?"—":`${Number(v)>0?"+":""}${Number(v).toFixed(2)}%`;
export default function CompanyPage(){const {symbol:raw}=useParams<{symbol:string}>();const symbol=raw.toUpperCase();const [detail,setDetail]=useState<CompanyDetail|null>(null);const [history,setHistory]=useState<MarketPrice[]>([]);const [portfolio,setPortfolio]=useState<PortfolioSummary|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{void Promise.all([getCompanyDetail(symbol),getCompanyHistory(symbol,365),getPortfolios()]).then(async([d,h,p])=>{setDetail(d);setHistory(h);for(const row of p){const s=await getPortfolioSummary(row.id).catch(()=>null);if(s?.holdings.some(x=>x.symbol===symbol)){setPortfolio(s);break}}}).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))},[symbol]);
 const trajectory=useMemo(()=>{if(history.length<2)return null;const first=Number(history[0].close),last=Number(history.at(-1)?.close);return (last/first-1)*100},[history]);
 if(loading)return <div className="page-wrap"><div className="panel h-96 skeleton"/></div>;if(error||!detail)return <div className="page-wrap"><div className="notice notice-error"><Icon name="warning"/>{error||"Company not found"}</div></div>;const latest=detail.latest_price;const holding=portfolio?.holdings.find(h=>h.symbol===symbol);
 return <div className="page-wrap"><header className="page-heading"><div><Link href="/markets" className="eyebrow">Markets / Company analyzer</Link><div className="mt-1 flex flex-wrap items-baseline gap-3"><h1 className="page-title">{symbol}</h1><span className="text-sm font-semibold text-[#334353]">{detail.company.name}</span></div><p className="page-subtitle">{detail.company.sector} · {detail.company.exchange.code}</p></div>{holding?<span className="badge badge-good">Held in {portfolio?.portfolio.name}</span>:<span className="badge">Not held</span>}</header>
 <div className="flex flex-wrap items-center justify-between gap-3 border-l-4 border-[#17324d] bg-white p-4"><div><p className="metric-label">Last traded price</p><p className="data-font mt-1 text-3xl font-semibold">PKR {latest?num(latest.close):"—"}</p></div><div className="text-right"><p className={`data-font text-lg font-semibold ${Number(latest?.change_percent)>=0?"positive":"negative"}`}>{pct(latest?.change_percent)}</p><p className="text-[11px] text-muted">{latest?.trade_date??"Date unavailable"} · {latest?.source??"Source unavailable"}</p></div></div>
 <div className="metric-strip mt-3 grid-cols-4"><Metric label="Period trajectory" value={pct(trajectory)}/><Metric label="Volume" value={latest?num(latest.volume,0):"—"}/><Metric label="Day range" value={latest?`${num(latest.low)}–${num(latest.high)}`:"—"}/><Metric label="Portfolio relevance" value={holding?`${pct(holding.unrealized_gain_loss_percent)} P&L`:"Not held"}/></div>
 <section className="panel mt-3"><div className="panel-head"><h2 className="panel-title">Price trajectory</h2><span className="text-[10px] text-muted">{history.length} database observations</span></div><div className="panel-body"><LineChart height={350} labels={history.map(x=>x.trade_date)} values={history.map(x=>Number(x.close))}/></div></section>
 <div className="mt-3 grid gap-3 xl:grid-cols-2"><Section title="Fundamentals"><Unavailable text="Structured company fundamentals are not exposed by the current frontend API."/></Section><Section title="Valuation & risk"><div className="grid grid-cols-2 gap-3"><Small label="Observed high" value={history.length?`PKR ${num(Math.max(...history.map(x=>Number(x.high))))}`:"—"}/><Small label="Observed low" value={history.length?`PKR ${num(Math.min(...history.map(x=>Number(x.low))))}`:"—"}/><Small label="Position value" value={holding?`PKR ${num(holding.market_value,0)}`:"—"}/><Small label="Position day P&L" value={holding?`PKR ${num(holding.day_change,0)}`:"—"}/></div></Section><Section title="Announcements & events"><Unavailable text="No structured announcements or event feed is available for this security."/></Section><Section title="Management plans"><Unavailable text="Search cited reports for management commentary; no verified plan summary was returned."/><Link href={`/research?symbol=${symbol}`} className="btn btn-secondary mt-3">Search company evidence</Link></Section></div>
 </div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><p className="metric-label">{label}</p><p className="metric-value data-font">{value}</p></div>}function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><h2 className="panel-title">{title}</h2></div><div className="panel-body">{children}</div></section>}function Unavailable({text}:{text:string}){return <div className="flex gap-2 text-xs text-muted"><Icon name="clock" size={15}/>{text}</div>}function Small({label,value}:{label:string;value:string}){return <div><p className="metric-label">{label}</p><p className="data-font mt-1 font-semibold">{value}</p></div>}
