"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect,useMemo,useState } from "react";
import { Icon } from "@/components/Icon";
import { LineChart } from "@/components/WorkstationChart";
import { CompanyDetail,CompanyResearch,MarketPrice,getCompanyDetail,getCompanyHistory,getCompanyResearch } from "@/lib/api";

const num=(value:unknown,digits=2)=>new Intl.NumberFormat("en-PK",{maximumFractionDigits:digits}).format(Number(value||0));
const pct=(value:unknown)=>value==null?"—":`${Number(value)>0?"+":""}${Number(value).toFixed(2)}%`;

export default function CompanyPage(){
  const {symbol:raw}=useParams<{symbol:string}>();const symbol=raw.toUpperCase();const [detail,setDetail]=useState<CompanyDetail|null>(null);const [research,setResearch]=useState<CompanyResearch|null>(null);const [history,setHistory]=useState<MarketPrice[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{void Promise.all([getCompanyDetail(symbol),getCompanyHistory(symbol,365),getCompanyResearch(symbol)]).then(([company,prices,analysis])=>{setDetail(company);setHistory(prices);setResearch(analysis)}).catch((reason:Error)=>setError(reason.message)).finally(()=>setLoading(false))},[symbol]);
  const trajectory=useMemo(()=>history.length<2?null:(Number(history.at(-1)?.close)/Number(history[0].close)-1)*100,[history]);
  if(loading)return <div className="page-wrap"><div className="panel h-96 skeleton"/></div>;
  if(error||!detail)return <div className="page-wrap"><div className="notice notice-error"><Icon name="warning"/>{error||"Company not found"}</div></div>;
  const latest=detail.latest_price;const relevance=research?.portfolio_relevance?.[0];const marketRisk=(research?.market_research?.risk??{}) as Record<string,unknown>;const derived=research?.derived_fundamentals;
  return <div className="page-wrap"><header className="page-heading"><div><Link href="/markets" className="eyebrow">Markets / Security research</Link><div className="mt-2 flex flex-wrap items-baseline gap-3"><h1 className="page-title">{symbol}</h1><span className="text-[15px] font-semibold text-[#3f454b]">{detail.company.name}</span></div><p className="page-subtitle">{detail.company.sector} · {detail.company.exchange.code}</p></div>{relevance?<span className="badge badge-good">Held · {pct(Number(relevance.weight)*100)} portfolio weight</span>:<span className="badge">Not held</span>}</header>
    <div className="source-rail flex flex-wrap items-end justify-between gap-5 px-6 py-5"><div><p className="metric-label">Last traded price</p><p className="data-font mt-2 text-[36px] font-semibold leading-none tracking-[-.045em]">PKR {latest?num(latest.close):"—"}</p></div><div className="sm:text-right"><p className={`data-font text-[17px] font-semibold ${Number(latest?.change_percent)>=0?"positive":"negative"}`}>{pct(latest?.change_percent)}</p><p className="mt-1 text-[11px] text-muted">{latest?.trade_date??"Date unavailable"} · {latest?.source??"Source unavailable"}</p></div></div>
    <div className="metric-strip mt-4 grid-cols-4"><Metric label="Period trajectory" value={pct(trajectory)}/><Metric label="Annual volatility" value={marketRisk.annual_volatility==null?"—":pct(Number(marketRisk.annual_volatility)*100)}/><Metric label="Historical VaR 95" value={marketRisk.historical_var_95==null?"—":pct(Number(marketRisk.historical_var_95)*100)}/><Metric label="Portfolio relevance" value={relevance?`PKR ${num(relevance.market_value,0)}`:"Not held"}/></div>
    <section className="panel mt-4"><div className="panel-head"><h2 className="panel-title">Price history</h2><span className="text-[11px] text-muted">{history.length} canonical observations</span></div><div className="panel-body"><LineChart height={380} labels={history.map(row=>row.trade_date)} values={history.map(row=>Number(row.close))}/></div></section>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><Section title="Normalized fundamentals">{research?.fundamentals.length?<Facts rows={research.fundamentals}/>:<Unavailable text="Normalized exact facts are unavailable. Documentary RAG is not substituted for numeric fundamentals."/>}</Section><Section title="Derived ratios & valuation">{derived&&Object.keys(derived.ratios??{}).length?<Facts rows={Object.entries(derived.ratios??{}).map(([taxonomy_key,row])=>({taxonomy_key,value:String(row.value??"—"),unit:"ratio",period_type:"derived",period_end:String(row.period_end??"—")}))}/>:<Unavailable text={String(derived?.valuation?.reason??"Compatible normalized facts are unavailable for deterministic ratios.")}/>}</Section><Section title="Announcements & events">{research?.events.length?<div className="divider-list">{research.events.map((event,index)=><article className="py-3 text-[13px]" key={String(event.id??index)}><strong>{String(event.title)}</strong><p className="mt-1 text-[11px] text-muted">{String(event.occurred_at??"Date unavailable")} · {String(event.event_type??"event")}</p></article>)}</div>:<Unavailable text="No structured sourced events are linked to this security."/>}</Section><Section title="Documents & management evidence">{research?.documents.length?<div className="divider-list">{research.documents.map((document,index)=><article className="py-3 text-[13px]" key={String(document.id??index)}><strong>{String(document.title)}</strong><p className="mt-1 text-[11px] text-muted">{String(document.published_date??"Date unavailable")} · {String(document.document_type??"document")}</p></article>)}</div>:<Unavailable text="No ownership-visible company documents were returned."/>}<Link href={`/research?symbol=${symbol}`} className="btn btn-secondary mt-4">Search cited evidence</Link></Section></div>
  </div>;
}
function Facts({rows}:{rows:Array<{taxonomy_key:string;value:string|number;unit:string;period_type:string;period_end:string}>}){return <div className="table-wrap"><table className="data-table"><thead><tr><th>Fact</th><th>Value</th><th>Period</th><th>Basis</th></tr></thead><tbody>{rows.slice(0,10).map((row,index)=><tr key={`${row.taxonomy_key}-${index}`}><td className="font-semibold">{row.taxonomy_key.replaceAll("_"," ")}</td><td className="data-font">{num(row.value)} {row.unit}</td><td>{row.period_end}</td><td>{row.period_type}</td></tr>)}</tbody></table></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><p className="metric-label">{label}</p><p className="metric-value data-font">{value}</p></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><h2 className="panel-title">{title}</h2></div><div className="panel-body">{children}</div></section>}
function Unavailable({text}:{text:string}){return <div className="flex gap-2 text-xs text-muted"><Icon name="clock" size={15}/>{text}</div>}
