"use client";
import {useEffect,useRef,useState} from "react";
import {BatchRequest,BatchPreview,JobStatus,previewResearchBatch,generateResearchBatch,getResearchJob} from "@/lib/api/research";
import {invalidateResearchCache} from "@/lib/api/client";
export function ResearchBatchControl({portfolioId,instrumentIds,onComplete}:{portfolioId?:string;instrumentIds?:string[];onComplete:()=>void}){
 const [preview,setPreview]=useState<BatchPreview|null>(null);const [job,setJob]=useState<JobStatus|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const requestRef=useRef<BatchRequest|null>(null);const sequence=useRef(0);const completion=useRef(onComplete);completion.current=onComplete;const scope=portfolioId??instrumentIds?.join(",")??"";
 useEffect(()=>{sequence.current++;setPreview(null);setJob(null);setError("");setBusy(false);requestRef.current=null},[scope]);
 useEffect(()=>{if(!job||["completed","failed","uncertain"].includes(job.status))return;let active=true;const timer=setInterval(()=>{void getResearchJob(job.id).then(next=>{if(!active)return;setJob(next);if(["completed","failed","uncertain"].includes(next.status)){invalidateResearchCache();completion.current()}}).catch(err=>{if(active)setError(err instanceof Error?err.message:"Job status unavailable")})},2000);return()=>{active=false;clearInterval(timer)}},[job?.id,job?.status]);
 async function previewBatch(){const id=++sequence.current;setBusy(true);setError("");try{const body:BatchRequest={client_request_id:crypto.randomUUID(),max_companies:8,max_calls:16,...(portfolioId?{portfolio_id:portfolioId}:{instrument_ids:instrumentIds})};requestRef.current=body;const result=await previewResearchBatch(body);if(id===sequence.current)setPreview(result)}catch(err){if(id===sequence.current)setError(err instanceof Error?err.message:"Preview failed")}finally{if(id===sequence.current)setBusy(false)}}
 async function generate(){if(!requestRef.current)return;const id=++sequence.current;setBusy(true);setError("");try{const next=await generateResearchBatch(requestRef.current);if(id!==sequence.current)return;setJob(next);if(next.status==="completed"){invalidateResearchCache();completion.current()}}catch(err){if(id===sequence.current)setError(err instanceof Error?err.message:"Generation failed")}finally{if(id===sequence.current)setBusy(false)}}
 const running=job&&!['completed','failed','uncertain'].includes(job.status);
 return <section className="rounded-lg border border-line bg-[#fafaf8] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xs font-semibold">Saved event explanations</h3><p className="mt-1 text-[11px] text-muted">Prepare report evidence and generate company explanations using your saved AI key.</p></div><button className="btn btn-secondary" disabled={busy||Boolean(running)||!scope} onClick={()=>void previewBatch()}>{busy?"Working…":"Preview generation"}</button></div>{preview&&!job?<div className="mt-4"><p className="text-xs">Up to <strong>{preview.maximum_calls} AI calls</strong> · {preview.companies.reduce((n,c)=>n+c.reports_to_index,0)} reports to index · {preview.companies.length} companies</p><p className="mt-2 text-[11px] text-muted">Estimated upper bound: {preview.estimated_input_tokens_upper_bound.toLocaleString()} input / {preview.estimated_output_tokens_upper_bound.toLocaleString()} output tokens. Actual usage is reported after generation.</p><div className="mt-2 flex flex-wrap gap-2">{preview.companies.map(c=><span className="badge" key={c.instrument_id}>{c.symbol} · {c.max_calls?`${c.max_calls} calls`:"cached"}</span>)}</div>{preview.provider_config?<p className="mt-2 text-[11px] text-muted">{preview.provider_config.provider} · {preview.provider_config.model}</p>:preview.maximum_calls?<p className="mt-2 text-xs negative">Save an active AI key in Settings first.</p>:null}<button className="btn btn-primary mt-3" disabled={busy||!preview.within_budget||Boolean(preview.maximum_calls&&!preview.provider_config)} onClick={()=>void generate()}>Generate saved explanations</button></div>:null}{job?<div className="mt-4" aria-live="polite"><p className="text-xs font-semibold">{job.status==="queued"?"Queued for research worker":job.status.replaceAll("_"," ")} · {job.reserved_calls}/{job.maximum_calls} calls reserved</p>{job.companies.map(c=><p className="mt-1 text-xs" key={c.id}>{c.result.symbol??c.instrument_id} · {c.status}{c.error_code?` · ${c.error_code.replaceAll("_"," ")}`:""}</p>)}<p className="mt-2 text-[11px] text-muted">Reported tokens: {job.actual_usage.input_tokens.toLocaleString()} input / {job.actual_usage.output_tokens.toLocaleString()} output{job.usage_complete?"":" · Usage incomplete"}</p></div>:null}{error?<p role="alert" className="mt-3 text-xs negative">{error}</p>:null}</section>
}
