"use client";
import Link from "next/link";
import {FormEvent,useEffect,useRef,useState} from "react";
import {Portfolio,AssistantResult,getPortfolios,searchInstruments,sendAssistantMessage,acknowledgeAssistantExecution,getCompanyResearch} from "@/lib/api";
import {CompanyIntelligence,PortfolioEventIntelligence,ResearchEventView,Evidence,getCompanyIntelligence,getPortfolioEventIntelligence,getEventFeed} from "@/lib/api/research";
import {ResearchEventCard,EvidenceDrawer} from "@/components/ResearchEventCard";
import {ResearchBatchControl} from "@/components/ResearchBatchControl";
import {AssistantResponse} from "@/components/AssistantResponse";

function Notice({error}:{error:string}){return <p role="alert" className="p-4 text-xs negative">{error}</p>}
function Empty(){return <p className="p-5 text-xs text-muted">No material events matched the available stored evidence. Missing coverage is not proof that no events affect this company.</p>}
const prompts={recent_changes:"Explain what changed in the supplied company's dated events, citing evidence. Separate facts, interpretation and missing evidence.",drivers:"Explain the company's documented business drivers, citing reports. Identify supported mechanisms and unknowns.",risks:"Explain the company's documented risks and conditions, citing reports. Separate evidence from hypotheses.",outlook:"Summarize dated management outlook and planned investments with citations. Distinguish management statements from your interpretation; do not invent forecasts."};
export function InlineResearchAnalysis({instrumentId,portfolioId,event}:{instrumentId:string;portfolioId?:string;event?:ResearchEventView}){
 const sequence=useRef(0); const [result,setResult]=useState<AssistantResult|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{sequence.current++;setResult(null);setError("");setBusy(false)},[instrumentId,portfolioId,event?.event_key]);
 async function analyze(personal:boolean){const id=++sequence.current;setBusy(true);setError("");try{const q=event?`Explain this stored event for the selected company: ${event.title}. Event key ${event.event_key}, dated ${event.occurred_at}. Read research.event_relevance and cite original evidence. Explain mechanisms, conditions and unknowns.${personal?" Include selected portfolio relevance and confirmed IPS.":" Use company evidence only."}`:personal?"Analyze the selected company's relevance to this selected portfolio and confirmed IPS, citing company evidence and exact database values. Explain risks, conditions and missing evidence.":"Analyze the selected company using exact database facts and cited reports. Explain changes, drivers, risks and outlook. Keep company intelligence separate from portfolio context.";const response=await sendAssistantMessage(q,personal?portfolioId:undefined,instrumentId,!personal);if(id!==sequence.current)return;setResult(response);const executionId=response.synthesis.execution_id;if(executionId)void acknowledgeAssistantExecution(executionId).catch(()=>undefined)}catch(err){if(id===sequence.current)setError(err instanceof Error?err.message:"Analysis failed")}finally{if(id===sequence.current)setBusy(false)}}
 return <div className="mt-4"><div className="flex flex-wrap gap-2"><button className="btn btn-primary" disabled={busy} onClick={()=>void analyze(false)}>{busy?"Analyzing…":event?"Analyze event for company":"Analyze company"}</button>{portfolioId?<button className="btn btn-secondary" disabled={busy} onClick={()=>void analyze(true)}>Analyze selected portfolio relevance</button>:null}</div>{error?<Notice error={error}/>:null}{result?<div className="mt-4"><AssistantResponse result={result}/></div>:null}</div>
}
export function CompanyIntelligencePanel({symbol,portfolioId}:{symbol:string;portfolioId?:string}){
 const [data,setData]=useState<CompanyIntelligence|null>(null);const [error,setError]=useState("");const [revision,setRevision]=useState(0);const [activeEvent,setActiveEvent]=useState<ResearchEventView|null>(null);
 useEffect(()=>{let active=true;setData(null);setActiveEvent(null);setError("");void getCompanyIntelligence(symbol).then(value=>{if(active)setData(value)}).catch(err=>{if(active)setError(err.message)});return()=>{active=false}},[symbol,revision]);
 return <section className="panel mt-4"><div className="panel-head"><div><h2 className="panel-title">What changed</h2><p className="mt-1 text-[11px] text-muted">Direct company events and supported indirect relationships.</p></div><span className="badge">Stored evidence</span></div>{error?<Notice error={error}/>:!data?<p className="p-5 text-xs text-muted">Loading company intelligence…</p>:<><div>{data.events.length?data.events.map(e=><ResearchEventCard event={e} key={e.event_key} analyze={()=>setActiveEvent(e)}/>):<Empty/>}</div><div className="border-t border-line p-5"><ResearchBatchControl instrumentIds={[data.instrument_id]} onComplete={()=>setRevision(v=>v+1)}/><details className="mt-4"><summary className="cursor-pointer text-xs font-semibold">Company exposure relationships</summary>{data.profile?<><p className="mt-3 text-[11px] text-muted">AI-proposed · {new Date(data.profile.generated_at).toLocaleDateString("en-PK")}</p>{data.profile.relationships.map((r,i)=><div className="mt-3" key={i}><span className="badge">{r.factor.replaceAll("_"," ")} · {r.channel.replaceAll("_"," ")}</span><p className="mt-2 text-xs leading-5">{r.mechanism}</p>{r.conditions.length?<p className="mt-1 text-xs text-muted">Conditions: {r.conditions.join(" · ")}</p>:null}<EvidenceDrawer evidence={data.profile!.evidence.filter(e=>r.evidence_ids.includes(e.id))}/></div>)}<p className="mt-3 text-xs text-muted">{data.profile.coverage_gaps.join(" · ")}</p></>:<p className="mt-3 text-xs text-muted">Exposure profile not generated. Indirect coverage is incomplete.</p>}<div className="mt-3 text-xs text-muted">{data.reports.length?data.reports.map(r=><p key={r.document_id}>{r.title} · {r.indexed?`${r.pages} pages indexed`:"Narrative not indexed"}</p>):"No eligible retained reports available."}</div></details><InlineResearchAnalysis instrumentId={data.instrument_id} portfolioId={portfolioId} event={activeEvent??undefined}/></div></>}</section>
}
export function CompanyPurposeEvidence({symbol}:{symbol:string}){
 const [evidence,setEvidence]=useState<Evidence[]>([]);const [purpose,setPurpose]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function select(key:keyof typeof prompts){setPurpose(key);setBusy(true);setError("");try{const result=await getCompanyResearch(symbol,{researchPurpose:key});const sections=result.context.sections as Record<string,{data?:unknown}>;const chunks=(sections.rag_evidence?.data??[]) as Array<Record<string,unknown>>;setEvidence(chunks.map(c=>{const citation=c.citation as Record<string,unknown>;return {id:String(c.id),document_id:String(c.document_id),page_number:c.page_number as number|null,title:String(citation?.title??"Title unavailable"),source_name:String(citation?.source_name??"Source unavailable"),source_url:c.source_url as string|null,text:String(c.chunk_text)}}))}catch(err){setError(err instanceof Error?err.message:"Evidence retrieval failed")}finally{setBusy(false)}}
 return <section className="panel mt-4"><div className="panel-head"><h2 className="panel-title">Explore company evidence</h2><Link className="text-xs text-accent" href={`/research?symbol=${encodeURIComponent(symbol)}`}>Search evidence</Link></div><div className="p-5"><div className="flex flex-wrap gap-2">{([['recent_changes','Changes'],['drivers','Drivers'],['risks','Risks'],['outlook','Outlook']] as const).map(([key,label])=><button className="btn btn-secondary" aria-pressed={purpose===key} disabled={busy} key={key} onClick={()=>void select(key)}>{label}</button>)}</div>{busy?<p className="mt-3 text-xs text-muted">Retrieving cited passages…</p>:purpose&&!evidence.length?<p className="mt-3 text-xs text-muted">No cited passages passed retrieval. Try the evidence search with a wider scope.</p>:null}{error?<Notice error={error}/>:null}<EvidenceDrawer evidence={evidence}/></div></section>
}
export function PortfolioEventPanel({portfolioId,compact=false}:{portfolioId:string;compact?:boolean}){
 const [data,setData]=useState<PortfolioEventIntelligence|null>(null);const [error,setError]=useState("");const [revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;setError("");setData(null);void getPortfolioEventIntelligence(portfolioId,compact?3:5).then(value=>{if(active)setData(value)}).catch(err=>{if(active)setError(err.message)});return()=>{active=false}},[portfolioId,compact,revision]);
 return <section className="panel"><div className="panel-head"><div><h2 className="panel-title">Events affecting your portfolio</h2><p className="mt-1 text-[11px] text-muted">{data?.portfolio_name??"Selected portfolio"} · Potential exposure, with cash included in portfolio weights.</p></div>{compact?<Link href={`/portfolios/${portfolioId}/research`} className="text-xs text-accent">View research</Link>:null}</div>{error?<Notice error={error}/>:!data?<p className="p-5 text-xs text-muted">Loading portfolio events…</p>:<>{!data.valuation_complete?<p className="p-4 text-xs text-muted">Valuation incomplete: {data.coverage.priced_holdings}/{data.coverage.holdings} holdings priced. Aggregate exposure percentage unavailable.</p>:null}{data.events.length?data.events.map(row=><div key={row.event.event_key}><ResearchEventCard event={row.event} weight={row.potentially_affected_weight} companies={row.companies.map(c=>c.symbol)}/><div className="px-5 pb-3">{row.companies.map(c=><details key={c.symbol} className="mt-2"><summary className="cursor-pointer text-xs font-semibold text-accent">{c.symbol} · {c.relationship_kind==="direct"?"Direct":"AI-proposed indirect"}</summary><ResearchEventCard event={{...row.event,relationship_kind:c.relationship_kind,subjects:[{subject_key:c.symbol}]}} brief={c.saved_brief}/></details>)}</div></div>):<Empty/>}<div className="border-t border-line p-4"><ResearchBatchControl portfolioId={portfolioId} onComplete={()=>setRevision(v=>v+1)}/></div></>}</section>
}
export function MarketEventPanel({symbol,portfolioId}:{symbol?:string;portfolioId?:string}){
 const sequence=useRef(0);
 const [events,setEvents]=useState<ResearchEventView[]>([]);const [error,setError]=useState("");const [loaded,setLoaded]=useState(false);const [affected,setAffected]=useState<Record<string,string|null>>({});const [cursor,setCursor]=useState<number|null>(null);
 useEffect(()=>{let active=true;sequence.current++;setAffected({});setLoaded(false);setError("");void getEventFeed(symbol).then(result=>{if(active){setEvents(result.events);setCursor(result.next_cursor);setLoaded(true)}}).catch(err=>{if(active){setError(err.message);setLoaded(true)}});void (portfolioId!==undefined?Promise.resolve(portfolioId):getPortfolios().then(rows=>rows.find(p=>p.is_default)?.id??"")).then(id=>id?getPortfolioEventIntelligence(id,20):null).then(result=>{if(active&&result)setAffected(Object.fromEntries(result.events.map(r=>[r.event.event_key,r.potentially_affected_weight])))}).catch(()=>undefined);return()=>{active=false}},[symbol,portfolioId]);
 async function more(){if(cursor===null)return;const id=sequence.current;try{const result=await getEventFeed(symbol,cursor);if(id!==sequence.current)return;setEvents(previous=>[...previous,...result.events]);setCursor(result.next_cursor)}catch(err){setError(err instanceof Error?err.message:"Events unavailable")}}
 return <section className="panel"><div className="panel-head"><div><h2 className="panel-title">Material market events</h2><p className="mt-1 text-[11px] text-muted">{symbol?`${symbol} · `:""}Dated events from stored source evidence.</p></div></div>{error?<Notice error={error}/>:!loaded?<p className="p-5 text-xs text-muted">Loading events…</p>:events.length?events.map(e=><ResearchEventCard key={e.event_key} event={e} weight={affected[e.event_key]}/>):<Empty/>}{cursor!==null?<button className="btn btn-secondary m-4" onClick={()=>void more()}>Show more events</button>:null}</section>
}
export function ResearchHub({symbol}:{symbol?:string|null}){
 const [portfolios,setPortfolios]=useState<Portfolio[]>([]);const [portfolioId,setPortfolioId]=useState("");const [query,setQuery]=useState("");const [matches,setMatches]=useState<{id:string;symbol:string;name:string}[]>([]);const [error,setError]=useState("");
 useEffect(()=>{void getPortfolios().then(rows=>{setPortfolios(rows);setPortfolioId(rows.find(p=>p.is_default)?.id??"")}).catch(err=>setError(err.message))},[]);
 async function search(e:FormEvent){e.preventDefault();try{setMatches(await searchInstruments(query));setError("")}catch(err){setError(err instanceof Error?err.message:"Company search failed")}}
 return <div className="mb-5 space-y-4"><div className="source-rail p-5"><div className="grid gap-4 md:grid-cols-[1fr_260px]"><form onSubmit={search} className="flex gap-2"><label className="field-label flex-1">Research a company<input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Company name or symbol" required/></label><button className="btn btn-secondary self-end">Find company</button></form><label className="field-label">Selected portfolio<select className="field" value={portfolioId} onChange={e=>setPortfolioId(e.target.value)}><option value="">No portfolio selected</option>{portfolios.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>{error?<Notice error={error}/>:null}{matches.length?<div className="mt-3 flex flex-wrap gap-2">{matches.map(m=><Link className="btn btn-secondary" key={m.id} href={`/companies/${encodeURIComponent(m.symbol)}`}>{m.symbol} · {m.name}</Link>)}</div>:null}</div><div className="grid items-start gap-4 xl:grid-cols-2"><MarketEventPanel symbol={symbol??undefined} portfolioId={portfolioId}/>{portfolioId?<PortfolioEventPanel portfolioId={portfolioId}/>:<section className="panel p-5 text-xs text-muted">Select a portfolio to see holding exposure. Company research is available for held and unheld companies.</section>}</div></div>
}
