"use client";
import Link from "next/link";
import {FormEvent,useEffect,useRef,useState} from "react";
import {Portfolio,getPortfolios,searchInstruments,getCompanyResearch} from "@/lib/api";
import {useAssistantWorkspace} from "@/components/AssistantWorkspace";
import {CompanyIntelligence,PortfolioEventIntelligence,ResearchEventView,Evidence,getCompanyIntelligence,getPortfolioEventIntelligence,getEventFeed} from "@/lib/api/research";
import {ResearchEventCard,EvidenceDrawer,ClaimText} from "@/components/ResearchEventCard";
import styles from "@/components/CompanyEvents.module.css";
import {ResearchBatchControl} from "@/components/ResearchBatchControl";

function Notice({error}:{error:string}){return <p role="alert" className="p-4 text-xs negative">{error}</p>}
function Empty(){return <p className="p-5 text-xs text-muted">No material events matched the available stored evidence. Missing coverage is not proof that no events affect this company.</p>}
const prompts={recent_changes:"Explain what changed in the supplied company's dated events, citing evidence. Separate facts, interpretation and missing evidence.",drivers:"Explain the company's documented business drivers, citing reports. Identify supported mechanisms and unknowns.",risks:"Explain the company's documented risks and conditions, citing reports. Separate evidence from hypotheses.",outlook:"Summarize dated management outlook and planned investments with citations. Distinguish management statements from your interpretation; do not invent forecasts."};
const eventQuestion=(event:ResearchEventView)=>`Explain this stored event for the selected company: ${event.title}. Event key ${event.event_key}, dated ${event.occurred_at}. Read research.event_relevance and cite original evidence. Explain mechanisms, conditions and unknowns. Include selected portfolio relevance and confirmed IPS.`;
const companyQuestion="Analyze the selected company using exact database facts and cited reports. Explain changes, drivers, risks and outlook. Keep company intelligence separate from portfolio context.";
const eventDay=(s:string)=>s.slice(0,10);
// One article can yield several event records with the same headline; show it once with all its types.
function groupEvents(events:ResearchEventView[]){const groups:{key:string;event:ResearchEventView;types:string[]}[]=[];for(const e of events){const key=`${eventDay(e.occurred_at)}|${e.title}`;const found=groups.find(g=>g.key===key);if(found){if(!found.types.includes(e.event_type))found.types.push(e.event_type)}else groups.push({key,event:e,types:[e.event_type]})}return groups}
function CompanyEventRow({group,symbol,onAsk}:{group:{event:ResearchEventView;types:string[]};symbol:string;onAsk:()=>void}){
 const {event,types}=group;const saved=event.saved_brief;const e=saved?.explanation;
 const companies=event.subjects.map(s=>s.subject_key);
 return <li className={styles.row}><time dateTime={event.occurred_at}>{new Date(event.occurred_at).toLocaleDateString("en-PK",{day:"numeric",month:"short",year:"numeric"})}</time><div>
  <h3>{event.title}</h3>
  <p className={styles.meta}>{types.map(t=>t.replaceAll("_"," ")).join(" · ")}{event.relationship_kind?` · ${event.relationship_kind==="direct"?"Direct":"AI-proposed indirect"}`:""}{(companies.length?companies:[symbol]).map(c=><span key={c}> · <Link href={`/companies/${encodeURIComponent(c)}`}>{c}</Link></span>)}</p>
  {e?<p className={styles.summary}>{e.why_it_matters[0]?.text??e.what_happened.text}</p>:null}
  <div className={styles.actions}><details className={styles.details}><summary>Event details and evidence</summary><div>{e?<><h4 className="text-xs font-semibold">What happened</h4><ClaimText claim={e.what_happened} evidence={saved!.evidence}/><h4 className="mt-3 text-xs font-semibold">Why it matters</h4>{e.why_it_matters.map((c,i)=><ClaimText key={i} claim={c} evidence={saved!.evidence}/>)}</>:null}<EvidenceDrawer evidence={saved?.evidence??event.evidence}/></div></details><button className={styles.link} onClick={onAsk}>Ask in chat →</button></div>
 </div></li>
}
export function CompanyIntelligencePanel({symbol,portfolioId}:{symbol:string;portfolioId?:string}){
 const [data,setData]=useState<CompanyIntelligence|null>(null);const [error,setError]=useState("");const [revision,setRevision]=useState(0);const workspace=useAssistantWorkspace();
 useEffect(()=>{let active=true;setData(null);setError("");void getCompanyIntelligence(symbol).then(value=>{if(active)setData(value)}).catch(err=>{if(active)setError(err.message)});return()=>{active=false}},[symbol,revision]);
 const groups=data?groupEvents(data.events):[];
 return <section><div className={styles.head}><div><h2>What changed</h2><p>Direct company events and supported indirect relationships, from stored evidence.</p></div>{workspace?<button className={styles.link} onClick={()=>workspace.askNew(companyQuestion)}>Ask about {symbol} in chat →</button>:null}</div>
 {error?<Notice error={error}/>:!data?<p className={styles.empty}>Loading company intelligence…</p>:<>
  {groups.length?<ol className={styles.list}>{groups.map(g=><CompanyEventRow key={g.key} group={g} symbol={symbol} onAsk={()=>workspace?.askNew(eventQuestion(g.event))}/>)}</ol>:<p className={styles.empty}>No material events matched the available stored evidence. Missing coverage is not proof that no events affect this company.</p>}
  <div className={styles.generate}><ResearchBatchControl instrumentIds={[data.instrument_id]} onComplete={()=>setRevision(v=>v+1)}/></div>
  <details className={styles.exposure}><summary>Company exposure relationships</summary>{data.profile?<><p className={styles.note}>AI-proposed · {new Date(data.profile.generated_at).toLocaleDateString("en-PK")}</p>{data.profile.relationships.map((r,i)=><div key={i}><p><strong>{r.factor.replaceAll("_"," ")} · {r.channel.replaceAll("_"," ")}</strong></p><p>{r.mechanism}</p>{r.conditions.length?<p className={styles.note}>Conditions: {r.conditions.join(" · ")}</p>:null}<EvidenceDrawer evidence={data.profile!.evidence.filter(x=>r.evidence_ids.includes(x.id))}/></div>)}<p className={styles.note}>{data.profile.coverage_gaps.join(" · ")}</p></>:<p className={styles.note}>Exposure profile not generated. Indirect coverage is incomplete.</p>}<p className={styles.note}>{data.reports.length?data.reports.map(r=>`${r.title} · ${r.indexed?`${r.pages} pages indexed`:"Narrative not indexed"}`).join(" | "):"No eligible retained reports available."}</p></details>
 </>}</section>
}
export function CompanyPurposeEvidence({symbol}:{symbol:string}){
 const [evidence,setEvidence]=useState<Evidence[]>([]);const [purpose,setPurpose]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function select(key:keyof typeof prompts){setPurpose(key);setBusy(true);setError("");try{const result=await getCompanyResearch(symbol,{researchPurpose:key});const sections=result.context.sections as Record<string,{data?:unknown}>;const chunks=(sections.rag_evidence?.data??[]) as Array<Record<string,unknown>>;setEvidence(chunks.map(c=>{const citation=c.citation as Record<string,unknown>;return {id:String(c.id),document_id:String(c.document_id),page_number:c.page_number as number|null,title:String(citation?.title??"Title unavailable"),source_name:String(citation?.source_name??"Source unavailable"),source_url:c.source_url as string|null,text:String(c.chunk_text)}}))}catch(err){setError(err instanceof Error?err.message:"Evidence retrieval failed")}finally{setBusy(false)}}
 return <section className="panel mt-4"><div className="panel-head"><h2 className="panel-title">Explore company evidence</h2><Link className="text-xs text-accent" href={`/research?symbol=${encodeURIComponent(symbol)}`}>Search evidence</Link></div><div className="p-5"><div className="flex flex-wrap gap-2">{([['recent_changes','Changes'],['drivers','Drivers'],['risks','Risks'],['outlook','Outlook']] as const).map(([key,label])=><button className="btn btn-secondary" aria-pressed={purpose===key} disabled={busy} key={key} onClick={()=>void select(key)}>{label}</button>)}</div>{busy?<p className="mt-3 text-xs text-muted">Retrieving cited passages…</p>:purpose&&!evidence.length?<p className="mt-3 text-xs text-muted">No cited passages passed retrieval. Try the evidence search with a wider scope.</p>:null}{error?<Notice error={error}/>:null}<EvidenceDrawer evidence={evidence}/></div></section>
}
export function PortfolioEventPanel({portfolioId,compact=false}:{portfolioId:string;compact?:boolean}){
 const [data,setData]=useState<PortfolioEventIntelligence|null>(null);const [error,setError]=useState("");const [revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;setError("");setData(null);void getPortfolioEventIntelligence(portfolioId,compact?3:5).then(value=>{if(active)setData(value)}).catch(err=>{if(active)setError(err.message)});return()=>{active=false}},[portfolioId,compact,revision]);
 return <section className="panel"><div className="panel-head"><div><h2 className="panel-title">Events affecting your portfolio</h2><p className="mt-1 text-[11px] text-muted">{data?.portfolio_name??"Selected portfolio"} · Potential exposure, with cash included in portfolio weights.</p></div>{compact?<Link href={`/portfolios/${portfolioId}/research`} className="text-xs text-accent">View research</Link>:null}</div>{error?<Notice error={error}/>:!data?<p className="p-5 text-xs text-muted">Loading portfolio events…</p>:<>{!data.valuation_complete?<p className="p-4 text-xs text-muted">Valuation incomplete: {data.coverage.priced_holdings}/{data.coverage.holdings} holdings priced. Aggregate exposure percentage unavailable.</p>:null}{data.events.length?data.events.map(row=><div key={row.event.event_key}><ResearchEventCard event={row.event} weight={row.potentially_affected_weight} companies={row.companies.map(c=>c.symbol)}/><div className="px-5 pb-3">{row.companies.map(c=><details key={c.symbol} className="mt-2"><summary className="cursor-pointer text-xs font-semibold text-accent">{c.symbol} · {c.relationship_kind==="direct"?"Direct":"AI-proposed indirect"}</summary><ResearchEventCard event={{...row.event,relationship_kind:c.relationship_kind,subjects:[{subject_key:c.symbol}]}} brief={c.saved_brief}/></details>)}</div></div>):<Empty/>}<div className="border-t border-line p-4"><ResearchBatchControl portfolioId={portfolioId} onComplete={()=>setRevision(v=>v+1)}/></div></>}</section>
}
export function MarketEventPanel({symbol,portfolioId}:{symbol?:string;portfolioId?:string}){
 const sequence=useRef(0);
 const [events,setEvents]=useState<ResearchEventView[]>([]);const [error,setError]=useState("");const [loaded,setLoaded]=useState(false);const [affected,setAffected]=useState<Record<string,string|null>>({});const [cursor,setCursor]=useState<number|null>(null);
 useEffect(()=>{let active=true;sequence.current++;setAffected({});setLoaded(false);setError("");void getEventFeed(symbol).then(result=>{if(active){setEvents(result.events);setCursor(result.next_cursor);setLoaded(true)}}).catch(err=>{if(active){setError(err.message);setLoaded(true)}});void (portfolioId!==undefined?Promise.resolve(portfolioId):getPortfolios().then(rows=>rows.find(p=>p.is_default)?.id??"")).then(id=>id?getPortfolioEventIntelligence(id,20):null).then(result=>{if(active&&result)setAffected(Object.fromEntries(result.events.map(r=>[r.event.event_key,r.potentially_affected_weight])))}).catch(()=>undefined);return()=>{active=false}},[symbol,portfolioId]);
 async function more(){if(cursor===null)return;const id=sequence.current;try{const result=await getEventFeed(symbol,cursor);if(id!==sequence.current)return;setEvents(previous=>[...previous,...result.events]);setCursor(result.next_cursor)}catch(err){setError(err instanceof Error?err.message:"Events unavailable")}}
 return <section className="panel"><div className="panel-head"><div><h2 className="panel-title">Material market events</h2><p className="mt-1 text-[11px] text-muted">{symbol?`${symbol} · `:""}Dated events from stored source evidence.</p></div></div>{error?<Notice error={error}/>:!loaded?<p className="p-5 text-xs text-muted">Loading events…</p>:events.length?events.map(e=><ResearchEventCard key={e.event_key} event={e} weight={affected[e.event_key]}/>):<Empty/>}{cursor!==null?<button className="btn btn-secondary m-4" onClick={()=>void more()}>Show more events</button>:null}</section>
}
export function ResearchHub({symbol}:{symbol?:string|null}){
 const [portfolios,setPortfolios]=useState<Portfolio[]>([]);const [portfolioId,setPortfolioId]=useState("");const [query,setQuery]=useState("");const [matches,setMatches]=useState<{id:string;symbol:string;name:string}[]>([]);const [error,setError]=useState("");
 useEffect(()=>{void getPortfolios().then(rows=>{setPortfolios(rows);setPortfolioId(rows.find(p=>p.is_default)?.id??"")}).catch(err=>setError(err.message))},[]);
 async function search(e:FormEvent){e.preventDefault();try{setMatches(await searchInstruments(query));setError("")}catch(err){setError(err instanceof Error?err.message:"Company search failed")}}
 return <div className="mb-5 space-y-4"><div className="source-rail p-5"><div className="grid gap-4 md:grid-cols-[1fr_260px]"><form onSubmit={search} className="flex gap-2"><label className="field-label flex-1">Research a company<input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Company name or symbol" required/></label><button className="btn btn-secondary self-end">Find company</button></form><label className="field-label">Selected portfolio<select className="field" value={portfolioId} onChange={e=>setPortfolioId(e.target.value)}><option value="">No portfolio selected</option>{portfolios.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>{error?<Notice error={error}/>:null}{matches.length?<div className="mt-3 flex flex-wrap gap-2">{matches.map(m=><Link className="btn btn-secondary" key={m.id} href={`/companies/${encodeURIComponent(m.symbol)}`}>{m.symbol} · {m.name}</Link>)}</div>:null}</div><div className="grid items-start gap-4 xl:grid-cols-2"><MarketEventPanel symbol={symbol??undefined} portfolioId={portfolioId}/>{portfolioId?<PortfolioEventPanel portfolioId={portfolioId}/>:<section className="panel p-5 text-xs text-muted">Select a portfolio to see holding exposure. Company research is available for held and unheld companies.</section>}</div></div>
}
