"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {Evidence,Claim,ResearchEventView,SavedBrief,getEvidencePage} from "@/lib/api/research";
const date=(s:string)=>new Date(s).toLocaleDateString("en-PK",{day:"numeric",month:"short",year:"numeric"});
export function EvidenceDrawer({evidence}:{evidence:Evidence[]}){
 const dialogRef=useRef<HTMLDialogElement>(null); const [page,setPage]=useState<{title:string;page_number:number;text:string}|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{if(page&&!dialogRef.current?.open)dialogRef.current?.showModal()},[page]);
 async function open(e:Evidence){if(!e.page_number)return;setBusy(true);setError("");try{setPage(await getEvidencePage(e.document_id,e.page_number))}catch(err){setError(err instanceof Error?err.message:"Evidence unavailable")}finally{setBusy(false)}}
 return <div className="mt-3 space-y-3">{evidence.map(e=><article className="rounded-lg border border-line p-3" key={e.id}><strong className="text-xs">{e.title}</strong><p className="mt-1 text-[11px] text-muted">{e.source_name} · {e.page_number?`Page ${e.page_number}`:"Page unavailable"}{e.published_date||e.published_at?` · ${e.published_date??date(e.published_at!)}`:""}</p><p className="mt-2 text-xs leading-5">{e.text}</p><div className="mt-2 flex gap-4">{e.source_url&&/^https?:\/\//.test(e.source_url)?<a className="text-xs font-semibold text-accent" href={e.source_url} target="_blank" rel="noreferrer">Open source</a>:null}{e.page_number?<button className="text-xs font-semibold text-accent" disabled={busy} onClick={()=>void open(e)}>Read page {e.page_number}</button>:null}</div></article>)}{error?<p role="alert" className="text-xs negative">{error}</p>:null}{page?<dialog ref={dialogRef} aria-label="Source page" className="fixed inset-0 m-0 h-screen w-screen max-w-none bg-transparent p-0 backdrop:bg-black/30 open:flex open:justify-end" onCancel={()=>setPage(null)} onClick={()=>setPage(null)}><section className="h-full w-full max-w-2xl overflow-auto bg-white p-6 shadow-xl" onClick={e=>e.stopPropagation()}><button autoFocus className="btn btn-secondary float-right" onClick={()=>setPage(null)}>Close</button><h3 className="pr-20 text-sm font-semibold">{page.title} · Page {page.page_number}</h3><p className="mt-6 whitespace-pre-wrap text-sm leading-6">{page.text}</p></section></dialog>:null}</div>
}
export function ClaimText({claim,evidence}:{claim:Claim;evidence:Evidence[]}){return <p className="mt-2 text-[13px] leading-6">{claim.text}{claim.evidence_ids.map(id=>{const e=evidence.find(x=>x.id===id);return e?<span key={id} className="ml-1 text-[10px] font-semibold text-accent" title={`${e.title} · Page ${e.page_number??"unavailable"}`}>[{e.page_number?`p.${e.page_number}`:"source"}]</span>:null})}{claim.fact_ids.length?<span className="ml-1 text-[10px] text-muted" title={claim.fact_ids.join(", ")}>[database facts]</span>:null}</p>}
export function ResearchEventCard({event,brief,weight,companies,analyze}:{event:ResearchEventView;brief?:SavedBrief|null;weight?:string|null;companies?:string[];analyze?:()=>void}){
 const saved=brief??event.saved_brief;const e=saved?.explanation;
 return <article className="border-b border-line px-5 py-4 last:border-b-0"><div className="flex flex-wrap gap-2"><span className={`badge ${event.materiality==="high"?"badge-warn":""}`}>{event.event_type.replaceAll("_"," ")}</span><span className="text-[11px] text-muted">{date(event.occurred_at)}</span>{event.relationship_kind?<span className="badge">{event.relationship_kind==="direct"?"Direct":"AI-proposed indirect"}</span>:null}{weight!==undefined?<span className="badge">{weight===null?"Portfolio weight unavailable":`${(Number(weight)*100).toFixed(1)}% potentially affected`}</span>:null}</div><h3 className="mt-2 text-sm font-semibold leading-6">{event.title}</h3><div className="mt-2 flex flex-wrap gap-2">{(companies??event.subjects.map(s=>s.subject_key)).map(s=><Link key={s} href={`/companies/${encodeURIComponent(s)}`} className="text-xs font-semibold text-accent">{s}</Link>)}</div>{e?<p className="mt-2 text-[13px] leading-6 text-muted">{e.why_it_matters[0]?.text??e.what_happened.text}</p>:<p className="mt-2 text-xs text-muted">Saved explanation not generated.</p>}<details className="mt-3"><summary className="cursor-pointer text-xs font-semibold text-accent">Event details and evidence</summary>{e?<div className="mt-3"><span className="badge">{e.status.replaceAll("_"," ")}</span><h4 className="mt-3 text-xs font-semibold">What happened</h4><ClaimText claim={e.what_happened} evidence={saved!.evidence}/><h4 className="mt-3 text-xs font-semibold">Why it matters</h4>{e.why_it_matters.map((c,i)=><ClaimText key={i} claim={c} evidence={saved!.evidence}/>)}{e.countereffects.length?<><h4 className="mt-3 text-xs font-semibold">Conditions and countereffects</h4>{e.countereffects.map((c,i)=><ClaimText key={i} claim={c} evidence={saved!.evidence}/>)}</>:null}{e.unknowns.length?<p className="mt-3 text-xs leading-5 text-muted">Unknown: {e.unknowns.join(" · ")}</p>:null}<p className="mt-3 text-[10px] text-muted">Generated {date(saved!.generated_at)} · Source event {date(event.occurred_at)}</p></div>:null}<EvidenceDrawer evidence={saved?.evidence??event.evidence}/></details>{analyze?<button className="btn btn-secondary mt-3" onClick={analyze}>Ask in chat</button>:null}</article>
}
