"use client";

import { FormEvent,Suspense,useEffect,useRef,useState } from "react";
import { useSearchParams } from "next/navigation";
import { Icon } from "@/components/Icon";
import { TermHelp } from "@/components/TermHelp";
import { AssistantResult,Portfolio,deactivateContextRefresh,getPortfolios,sendAssistantMessage } from "@/lib/api";

export default function AssistantPage(){return <Suspense fallback={<div className="page-wrap"><div className="panel h-96 skeleton"/></div>}><AssistantContent/></Suspense>}
function AssistantContent(){
  const params=useSearchParams();const instrumentId=params?.get("instrument_id")??"";const [portfolios,setPortfolios]=useState<Portfolio[]>([]);const [portfolioId,setPortfolioId]=useState(params?.get("portfolio_id")??"");const [question,setQuestion]=useState(params?.get("question")??"");const [result,setResult]=useState<AssistantResult|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  // Portfolio scope defaults to Market-wide and is only ever changed by an explicit
  // user selection; the list load must never silently switch a question's scope.
  const requestSeq=useRef(0);
  useEffect(()=>{void getPortfolios().then(setPortfolios).catch((reason:unknown)=>setError(reason instanceof Error?`Portfolio scope request failed: ${reason.message}`:"Portfolio scope request failed"))},[]);
  useEffect(()=>{const refreshId=result?.refresh_request_id;if(!refreshId)return;return()=>{void deactivateContextRefresh(refreshId).catch(()=>undefined)}},[result?.refresh_request_id]);
  async function ask(e:FormEvent){
    e.preventDefault();
    const askedQuestion=question;const askedPortfolioId=portfolioId;
    const id=++requestSeq.current;
    setLoading(true);setError("");
    try{
      const response=await sendAssistantMessage(askedQuestion,askedPortfolioId||undefined,instrumentId||undefined);
      if(id===requestSeq.current) setResult(response);
    }catch(err){
      if(id===requestSeq.current) setError(err instanceof Error?err.message:"Assistant failed");
    }finally{
      if(id===requestSeq.current) setLoading(false);
    }
  }
  return <div className="page-wrap">
    <header className="page-heading"><div><p className="eyebrow">Grounded decision support</p><h1 className="page-title">Research assistant</h1><p className="page-subtitle">Ask about a security, your portfolio, risks, or the evidence behind a view.</p></div><span className="badge badge-good">Grounded analysis</span></header>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><main className="grid min-w-0 content-start gap-5"><form onSubmit={ask} className="source-rail p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-[14px] font-semibold">New research question</h2><label className="field-label w-full sm:w-60"><span className="sr-only">Portfolio scope</span><select aria-label="Portfolio scope" className="field" value={portfolioId} onChange={e=>setPortfolioId(e.target.value)}><option value="">Market-wide</option>{portfolios.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><label className="field-label">Question<textarea className="field mt-1 text-sm leading-6" rows={5} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Where is risk concentrated, what changed, and what evidence is still missing?" required/></label><div className="mt-4 flex justify-end"><button className="btn btn-primary" disabled={loading}><Icon name="assistant"/>{loading?"Gathering evidence…":"Analyze question"}</button></div></form>{error?<div className="notice notice-error" role="alert"><Icon name="warning"/>{error}</div>:null}{result?<Response result={result}/>:<div className="rounded-xl bg-surface px-6 py-12 text-center"><Icon name="assistant" size={28} className="mx-auto text-muted"/><strong className="mt-3 block text-[13px]">Ask a portfolio or market question</strong><span className="mt-1 block text-[12px] text-muted">The response will show its evidence boundaries and freshness warnings.</span></div>}</main><aside className="grid h-fit gap-4 xl:sticky xl:top-20"><section className="panel"><div className="panel-head"><h2 className="panel-title">Analysis scope</h2></div><div className="panel-body space-y-4"><Scope label="Portfolio" value={portfolios.find(p=>p.id===portfolioId)?.name??"Market-wide"}/><Scope label="Numerical facts" value="Deterministic services"/><Scope label="Narrative evidence" value="Cited documents"/><Scope label="Portfolio changes" value="Proposal only"/></div></section></aside></div>
  </div>;
}

function Response({result}:{result:AssistantResult}){const llm=result.synthesis?.mode==="llm_grounded";return <div className="grid gap-5"><section className="source-rail px-6 py-5"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><h2 className="text-[14px] font-semibold">Answer</h2><span className={`badge ${llm?"badge-good":"badge-warn"}`}>{llm?`AI synthesis · ${result.synthesis.provider} · ${result.synthesis.model}`:"Deterministic fallback"}</span></div><span className="text-[11px] text-muted">{new Date(result.created_at).toLocaleString()}</span></div><AnswerText text={result.answer}/></section>{result.calculated_evidence.length?<Evidence title="Key numerical evidence" rows={result.calculated_evidence}/>:null}{result.source_citations.length?<Citations rows={result.source_citations}/>:null}{result.uncertainty.length||result.freshness_warnings.length?<section className="panel"><div className="panel-head"><h2 className="panel-title">Uncertainty and missing data</h2><span className="badge badge-warn">Review</span></div><div className="divider-list">{[...result.uncertainty,...result.freshness_warnings].map((x,i)=><div className="flex gap-3 px-4 py-3 text-[13px]" key={i}><Icon name="warning" size={15} className="mt-0.5 shrink-0 text-[#a86f18]"/><span>{x}</span></div>)}</div></section>:null}{result.tool_trace.length?<details className="panel"><summary className="cursor-pointer px-4 py-3 text-[12px] font-semibold">How this answer was built</summary><p className="border-t border-line px-4 py-3 text-[12px] text-muted">Used {result.tool_trace.length} grounded data step{result.tool_trace.length===1?"":"s"}. Numerical portfolio facts came from deterministic services; {llm?"the configured model consolidated and interpreted the retrieved context":"a deterministic fallback organized the available facts"}.</p></details>:null}</div>}
function AnswerText({text}:{text:string}){const sections=text.split(/\n\s*\n/).map(value=>value.trim()).filter(Boolean);if(sections.length<3)return <p className="mt-4 whitespace-pre-wrap text-[14px] leading-7">{text}</p>;return <div className="mt-4 grid gap-5">{sections.map((section,index)=>{if(section==="Integrated outlook")return <p className="eyebrow" key={index}>Integrated security outlook</p>;const [heading,...body]=section.split("\n");if(!body.length)return <p className="text-[14px] leading-7" key={index}>{section}</p>;return <section key={index}><h3 className="text-[12px] font-semibold text-[#3f454b]">{heading}</h3><p className="mt-1 text-[14px] leading-7">{body.join(" ")}</p></section>})}</div>}
function Evidence({title,rows}:{title:string;rows:Array<Record<string,unknown>>}){return <section className="panel"><div className="panel-head"><h2 className="panel-title">{title}</h2><span className="text-[11px] text-muted">{rows.length} item{rows.length===1?"":"s"}</span></div><div className="divider-list">{rows.map((r,i)=><div className="px-5 py-4" key={i}><DataRecord value={r}/></div>)}</div></section>}
function Citations({rows}:{rows:Array<Record<string,unknown>>}){return <section className="panel"><div className="panel-head"><h2 className="panel-title">Cited company evidence</h2><span className="text-[11px] text-muted">{rows.length} source{rows.length===1?"":"s"}</span></div><div className="divider-list">{rows.map((row,index)=><article className="px-5 py-4" key={String(row.id??index)}><div className="flex flex-wrap items-center gap-2"><strong className="text-[13px]">{String(row.title??"Untitled source")}</strong>{row.symbol?<span className="badge">{String(row.symbol)}</span>:null}</div>{row.quote_snippet?<p className="mt-2 text-[12px] leading-5 text-muted">{String(row.quote_snippet)}</p>:null}<p className="mt-2 text-[11px] text-muted">{String(row.source_name??"Source unavailable")}{row.page_number?` · page ${String(row.page_number)}`:""}</p></article>)}</div></section>}
function DataRecord({value}:{value:Record<string,unknown>}){const hidden=new Set(["evidence_id","chunk_id","document_id","run_id","unit"]);return <dl className="grid gap-x-5 gap-y-2 sm:grid-cols-[150px_1fr]">{Object.entries(value).filter(([k,v])=>!hidden.has(k)&&v!==null&&v!==undefined).map(([k,v])=>{const formatted=formatEvidence(k,v,value.unit);return <div className="contents" key={k}><dt className="text-[11px] font-semibold capitalize text-muted">{k.replaceAll("_"," ")}</dt><dd className="m-0 break-words text-[12px] leading-5"><span className="inline-flex items-center gap-1">{formatted}{k==="metric"?<TermHelp term={formatted}/>:null}</span></dd></div>})}</dl>}
function formatEvidence(key:string,value:unknown,unit:unknown){const labels:Record<string,string>={current_weight:"Current portfolio weight",sector_headroom:"Sector headroom",average_holding_correlation:"Average holding correlation",annual_volatility:"Annual volatility",macro_regime:"Macro regime",percentage_risk_contribution:"Risk contribution"};if(key==="metric")return labels[String(value)]??String(value).replaceAll("_"," ");if(typeof value==="number"&&(key==="value"||key==="limit")){if(unit==="decimal"||unit==="percentage_point")return `${(value*100).toFixed(2)}%`;if(unit==="PKR")return `PKR ${new Intl.NumberFormat("en-PK",{maximumFractionDigits:0}).format(value)}`;return new Intl.NumberFormat("en-PK",{maximumFractionDigits:3}).format(value)}if(typeof value==="object")return Array.isArray(value)?value.map(String).join(", "):Object.entries(value as Record<string,unknown>).map(([a,b])=>`${a.replaceAll("_"," ")}: ${String(b)}`).join(" · ");return String(value).replaceAll("_"," ")}
function Scope({label,value}:{label:string;value:string}){return <div><p className="metric-label">{label}</p><p className="mt-1 text-[12px] font-semibold">{value}</p></div>}
