"use client";

import { FormEvent,useEffect,useState } from "react";
import { Icon } from "@/components/Icon";
import { AssistantResult,Portfolio,getPortfolios,sendAssistantMessage } from "@/lib/api";

export default function AssistantPage(){
  const [portfolios,setPortfolios]=useState<Portfolio[]>([]);const [portfolioId,setPortfolioId]=useState("");const [question,setQuestion]=useState("");const [result,setResult]=useState<AssistantResult|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{void getPortfolios().then(rows=>{setPortfolios(rows);setPortfolioId(rows.find(r=>r.is_default)?.id??rows[0]?.id??"")}).catch((reason:unknown)=>setError(reason instanceof Error?`Portfolio scope request failed: ${reason.message}`:"Portfolio scope request failed"))},[]);
  async function ask(e:FormEvent){e.preventDefault();setLoading(true);setError("");try{setResult(await sendAssistantMessage(question,portfolioId||undefined))}catch(err){setError(err instanceof Error?err.message:"Assistant failed")}finally{setLoading(false)}}
  return <div className="page-wrap">
    <header className="page-heading"><div><p className="eyebrow">Grounded decision support</p><h1 className="page-title">Research assistant</h1><p className="page-subtitle">A serious analysis surface that keeps conclusions, evidence, uncertainty and audit trace distinct.</p></div><span className="badge badge-good">Evidence required</span></header>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><main className="grid min-w-0 content-start gap-5"><form onSubmit={ask} className="source-rail p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-[14px] font-semibold">New research question</h2><label className="field-label w-full sm:w-60"><span className="sr-only">Portfolio scope</span><select aria-label="Portfolio scope" className="field" value={portfolioId} onChange={e=>setPortfolioId(e.target.value)}><option value="">Market-wide</option>{portfolios.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><label className="field-label">Question<textarea className="field mt-1 text-sm leading-6" rows={5} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Where is risk concentrated, what changed, and what evidence is still missing?" required/></label><div className="mt-4 flex justify-end"><button className="btn btn-primary" disabled={loading}><Icon name="assistant"/>{loading?"Gathering evidence…":"Analyze question"}</button></div></form>{error?<div className="notice notice-error" role="alert"><Icon name="warning"/>{error}</div>:null}{result?<Response result={result}/>:<div className="rounded-xl bg-surface px-6 py-12 text-center"><Icon name="assistant" size={28} className="mx-auto text-muted"/><strong className="mt-3 block text-[13px]">Ask a portfolio or market question</strong><span className="mt-1 block text-[12px] text-muted">The response will show its evidence boundaries and freshness warnings.</span></div>}</main><aside className="grid h-fit gap-4 xl:sticky xl:top-20"><section className="panel"><div className="panel-head"><h2 className="panel-title">Analysis scope</h2></div><div className="panel-body space-y-4"><Scope label="Portfolio" value={portfolios.find(p=>p.id===portfolioId)?.name??"Market-wide"}/><Scope label="Numerical facts" value="Structured database"/><Scope label="Narrative evidence" value="Cited documents"/><Scope label="Execution" value="No trade placement"/></div></section><div className="notice"><Icon name="warning"/><span>Verify missing or stale evidence before acting.</span></div></aside></div>
  </div>;
}

function Response({result}:{result:AssistantResult}){return <div className="grid gap-5"><section className="source-rail px-6 py-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-[14px] font-semibold">Conclusion</h2><span className="text-[11px] text-muted">{new Date(result.created_at).toLocaleString()}</span></div><p className="mt-4 whitespace-pre-wrap text-[14px] leading-7">{result.answer}</p></section><Evidence title="Quantitative evidence" rows={result.calculated_evidence} empty="No calculated evidence was returned."/><Evidence title="Document evidence and sources" rows={result.source_citations} empty="No cited document evidence was returned."/>{result.uncertainty.length||result.freshness_warnings.length?<section className="panel"><div className="panel-head"><h2 className="panel-title">Uncertainty and missing data</h2><span className="badge badge-warn">Review</span></div><div className="divider-list">{[...result.uncertainty,...result.freshness_warnings].map((x,i)=><div className="flex gap-3 px-4 py-3 text-[13px]" key={i}><Icon name="warning" size={15} className="mt-0.5 shrink-0 text-[#a86f18]"/><span>{x}</span></div>)}</div></section>:null}<details className="panel"><summary className="cursor-pointer px-4 py-3 text-[12px] font-semibold">Analysis trace · {result.tool_trace.length} steps</summary><div className="divider-list border-t border-line">{result.tool_trace.map((x,i)=><div className="p-4" key={i}><p className="metric-label">Step {i+1}</p><DataRecord value={x}/></div>)}</div></details></div>}
function Evidence({title,rows,empty}:{title:string;rows:Array<Record<string,unknown>>;empty:string}){return <section className="panel"><div className="panel-head"><h2 className="panel-title">{title}</h2><span className="text-[11px] text-muted">{rows.length} item{rows.length===1?"":"s"}</span></div>{rows.length?<div className="divider-list">{rows.map((r,i)=><div className="px-5 py-4" key={i}><DataRecord value={r}/></div>)}</div>:<div className="empty-state !min-h-24">{empty}</div>}</section>}
function DataRecord({value}:{value:Record<string,unknown>}){return <dl className="grid gap-x-5 gap-y-2 sm:grid-cols-[150px_1fr]">{Object.entries(value).filter(([,v])=>v!==null&&v!==undefined).map(([k,v])=><div className="contents" key={k}><dt className="text-[11px] font-semibold capitalize text-muted">{k.replaceAll("_"," ")}</dt><dd className="m-0 break-words text-[12px] leading-5">{typeof v==="object"?Array.isArray(v)?v.map(String).join(", "):Object.entries(v as Record<string,unknown>).map(([a,b])=>`${a}: ${String(b)}`).join(" · "):String(v)}</dd></div>)}</dl>}
function Scope({label,value}:{label:string;value:string}){return <div><p className="metric-label">{label}</p><p className="mt-1 text-[12px] font-semibold">{value}</p></div>}
