"use client";

import { useEffect,useMemo,useState } from "react";
import { Icon } from "@/components/Icon";
import { Portfolio,acknowledgeAlert,getAlerts,getPortfolios } from "@/lib/api";

const val=(r:Record<string,unknown>,...keys:string[])=>{for(const k of keys)if(r[k]!=null)return String(r[k]);return""};
const severityLabel:Record<string,string>={critical:"Critical",high:"High priority",medium:"Warnings",warning:"Warnings",low:"Informational",info:"Informational"};
const percent=(value:unknown)=>value==null?"Not available":`${(Number(value)*100).toFixed(1)}%`;

export default function MonitoringPage(){
  const [rows,setRows]=useState<Array<Record<string,unknown>>>([]);const [portfolios,setPortfolios]=useState<Portfolio[]>([]);const [portfolio,setPortfolio]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{void getPortfolios().then(setPortfolios).catch(()=>{})},[]);
  useEffect(()=>{setLoading(true);void getAlerts(portfolio||undefined).then(setRows).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))},[portfolio]);
  async function acknowledge(id:string){try{await acknowledgeAlert(id);setRows(r=>r.filter(x=>String(x.id)!==id))}catch(e){setError(e instanceof Error?e.message:"Could not acknowledge alert")}}
  const groups=useMemo(()=>Object.groupBy(rows,r=>val(r,"severity")||"info"),[rows]);const order=["critical","high","medium","warning","low","info"];
  const portfolioName=(row:Record<string,unknown>)=>portfolios.find(p=>p.id===val(row,"portfolio_id"))?.name??val(row,"portfolio_name")??"Portfolio scope";
  return <div className="page-wrap"><header className="page-heading"><div><p className="eyebrow">Exception management</p><h1 className="page-title">Monitoring</h1><p className="page-subtitle">An ordered queue of active exceptions, freshness issues and mandate breaches that require attention.</p></div><select aria-label="Portfolio filter" className="field w-full sm:w-72" value={portfolio} onChange={e=>setPortfolio(e.target.value)}><option value="">All portfolios</option>{portfolios.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></header>
    <div className="metric-strip mb-5 grid-cols-4"><Metric label="Critical" value={String((groups.critical??[]).length)} tone={(groups.critical??[]).length?"negative":""}/><Metric label="High priority" value={String((groups.high??[]).length)} tone={(groups.high??[]).length?"negative":""}/><Metric label="Warnings" value={String((groups.medium??[]).length+(groups.warning??[]).length)}/><Metric label="Total open" value={String(rows.length)}/></div>
    {error?<div className="notice notice-error mb-4" role="alert"><Icon name="warning"/>{error}</div>:null}
    {loading?<div className="panel h-72 skeleton"/>:rows.length?<div className="panel">{order.filter(k=>groups[k]?.length).map(severity=><section key={severity}><div className="flex items-center justify-between bg-[#fafaf8] px-5 py-3"><h2 className="text-[12px] font-semibold">{severityLabel[severity]}</h2><span className={`badge ${severity==="critical"||severity==="high"?"badge-bad":"badge-warn"}`}>{groups[severity]?.length} open</span></div><div className="divider-list">{groups[severity]?.map((r,i)=>{const id=String(r.id??i),classification=val(r,"classification");return <article key={id} className="grid gap-4 px-5 py-4 md:grid-cols-[170px_1fr_auto]"><div><span className={`badge ${classification==="mandate_breach"?"badge-bad":"badge-warn"}`}>{classification==="mandate_breach"?"Mandate breach":"Monitoring warning"}</span><p className="mt-2 text-[11px] font-semibold text-ink">{val(r,"rule_type","category","alert_type")||"Portfolio exception"}</p><p className="mt-1 text-[11px] text-muted">{portfolioName(r)}</p><p className="data-font mt-1 text-[10px] text-muted">Created {val(r,"created_at","triggered_at")||"time unavailable"}</p></div><div><p className="text-[13px] font-semibold">{val(r,"message","title")||"Alert details unavailable"}</p><dl className="mt-3 grid gap-2 text-[11px] sm:grid-cols-4"><Evidence label="Rule threshold" value={percent(r.threshold&&typeof r.threshold==="object"?(r.threshold as Record<string,unknown>).maximum:null)}/><Evidence label="Current value" value={percent(r.current_value)}/><Evidence label="Related IPS limit" value={percent(r.related_ips_limit)}/><Evidence label="Data as of" value={val(r,"data_as_of")||"Unavailable"}/></dl><p className="mt-3 text-[11px] text-muted">{r.rule_enabled===false?"Rule is no longer active.":classification==="mandate_breach"?"This also breaches the confirmed IPS.":"This threshold is stricter than, or separate from, the confirmed IPS. It is a warning, not a mandate breach."}</p></div><button className="btn btn-secondary self-center" onClick={()=>acknowledge(id)}>Acknowledge</button></article>})}</div></section>)}</div>:<div className="rounded-xl bg-surface py-14 text-center"><Icon name="check" size={28} className="mx-auto text-accent"/><strong className="mt-3 block text-[13px]">No active exceptions</strong><span className="mt-1 block text-[12px] text-muted">Monitoring has not returned an alert for the selected scope.</span></div>}
  </div>;
}

function Metric({label,value,tone=""}:{label:string;value:string;tone?:string}){return <div className="metric"><p className="metric-label">{label}</p><p className={`metric-value data-font ${tone}`}>{value}</p></div>}
function Evidence({label,value}:{label:string;value:string}){return <div><dt className="text-muted">{label}</dt><dd className="data-font mt-0.5 font-semibold">{value}</dd></div>}
