"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Icon } from "@/components/Icon";
import { Company, DataHealth, MacroRegime, MarketFreshness, MarketOverview, MarketPrice, getCompanies, getDataHealth, getMacroRegime, getMarketFreshness, getMarketOverview } from "@/lib/api";

const num=(v:unknown,d=2)=>new Intl.NumberFormat("en-PK",{maximumFractionDigits:d,notation:Number(v)>999999?"compact":"standard"}).format(Number(v||0));
const pct=(v:unknown)=>v==null?"—":`${Number(v)>0?"+":""}${Number(v).toFixed(2)}%`;
const tone=(v:unknown)=>Number(v)>0?"positive":Number(v)<0?"negative":"muted";

type DirectoryState={status:"loading"|"success"|"error";query:string;rows:Company[];error?:string};

export default function MarketPage(){
  const [overview,setOverview]=useState<MarketOverview|null>(null);const [fresh,setFresh]=useState<MarketFreshness|null>(null);const [regime,setRegime]=useState<MacroRegime|null>(null);const [health,setHealth]=useState<DataHealth|null>(null);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [showDirectory,setShowDirectory]=useState(true);
  const [directory,setDirectory]=useState<DirectoryState>({status:"loading",query:"",rows:[]});
  const requestId=useRef(0);
  useEffect(()=>{void Promise.all([getMarketOverview(),getMarketFreshness(),getMacroRegime(),getDataHealth().catch(()=>null)]).then(([o,f,r,h])=>{setOverview(o);setFresh(f);setRegime(r);setHealth(h)}).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))},[]);
  useEffect(()=>{
    const normalized=query.trim();
    const id=++requestId.current;
    const controller=new AbortController();
    const timer=setTimeout(()=>{
      setDirectory({status:"loading",query:normalized,rows:[]});
      getCompanies(normalized,{signal:controller.signal}).then(rows=>{
        if(id===requestId.current)setDirectory({status:"success",query:normalized,rows});
      }).catch((reason:unknown)=>{
        if(!controller.signal.aborted&&id===requestId.current)setDirectory({status:"error",query:normalized,rows:[],error:reason instanceof Error?reason.message:"Company directory request failed"});
      });
    },250);
    return()=>{clearTimeout(timer);controller.abort()};
  },[query]);
  if(loading)return <div className="page-wrap"><div className="panel h-96 skeleton"/></div>;
  if(error)return <div className="page-wrap"><div className="notice notice-error"><Icon name="warning"/>{error}</div></div>;
  const snap=overview?.snapshot;const sectors=overview?.sectors??[];const adv=sectors.reduce((a,s)=>a+s.advancers,0),dec=sectors.reduce((a,s)=>a+s.decliners,0);
  return <div className="page-wrap">
    <header className="page-heading"><div><p className="eyebrow">Pakistan Stock Exchange</p><h1 className="page-title">Market intelligence</h1><p className="page-subtitle">Benchmark status, breadth, sector leadership and liquidity from structured market observations.</p></div><div className="flex w-full flex-wrap gap-2 sm:w-auto"><button className="btn btn-secondary" onClick={()=>setShowDirectory(!showDirectory)}><Icon name="settings"/>{showDirectory?"Hide directory":"Show directory"}</button><label className="relative min-w-0 flex-1 sm:w-64"><span className="sr-only">Search companies</span><input className="field pl-9" placeholder="Search companies" value={query} onChange={e=>setQuery(e.target.value)}/><Icon name="search" className="absolute left-3 top-3 text-muted"/></label></div></header>
    {fresh?.provider_mode_warning?<div className="notice notice-warn mb-2" role="alert"><Icon name="warning"/><span><strong>MOCK / SYNTHETIC DATA.</strong> {fresh.provider_mode_warning}</span></div>:null}
    {fresh?.ingestion_staleness_warning?<div className="notice notice-warn mb-2"><Icon name="clock"/><span>{fresh.ingestion_staleness_warning}</span></div>:null}
    {fresh?.backup_warning?<div className="notice notice-warn mb-4"><Icon name="warning"/><span>{fresh.backup_warning}</span></div>:null}
    <div className="source-rail flex flex-wrap items-end justify-between gap-5 px-6 py-5"><div><div className="flex items-center gap-2"><span className={`badge ${fresh?.is_stale?"badge-warn":"badge-good"}`}>{fresh?.is_stale?"Stale data":"Current data"}</span><span className="text-[11px] text-muted">{fresh?.latest_trade_date??"Trade date unavailable"}</span></div><p className="mt-4 text-[15px] font-semibold">{snap?.index_name??"Market index unavailable"}</p><p className="mt-1 text-[11px] text-muted">{fresh?.latest_used_provider??fresh?.latest_source??"Source unavailable"}</p></div><div className="sm:text-right"><p className="data-font text-[36px] font-semibold leading-none tracking-[-.045em]">{snap?num(snap.index_value):"—"}</p><p className={`data-font mt-2 text-[15px] font-semibold ${tone(snap?.index_change_percent)}`}>{pct(snap?.index_change_percent)}</p></div></div>
    <dl className="mt-4 grid gap-px overflow-hidden rounded-xl border border-line bg-line text-xs sm:grid-cols-6"><DataState label="Provider mode" value={fresh?.market_data_mode??"Unavailable"}/><DataState label="Trade date" value={fresh?.latest_trade_date??"Unavailable"}/><DataState label="Trade date status" value={fresh?.trade_date_status?.replaceAll("_"," ")??"Unknown"}/><DataState label="Ingestion age" value={fresh?.ingestion_age_seconds==null?"Unavailable":`${Math.round(fresh.ingestion_age_seconds/60)} min`}/><DataState label="Fallback provider" value={fresh?.fallback_provider_active?"Active":"Not active"}/><DataState label="Exchange session" value={fresh?.exchange_session_status??"Unknown"}/></dl>
    {fresh?.exchange_session_note?<p className="mt-1 text-[10px] text-muted">{fresh.exchange_session_note}</p>:null}
    <details className="panel mt-4"><summary className="panel-head cursor-pointer"><span className="panel-title">Data health</span><span className="text-[11px] text-muted">{health?`${health.sources.filter(row=>row.status==="healthy").length} healthy · ${health.sources.filter(row=>row.status!=="healthy").length} need attention`:"Health status unavailable"}</span></summary>{health?<div className="table-wrap"><table className="data-table"><thead><tr><th>Source</th><th>Status</th><th>Latest data</th><th>Last success</th><th>Run accounting</th><th>Diagnostic</th></tr></thead><tbody>{health.sources.map(row=><tr key={row.source}><td className="font-semibold">{row.source}</td><td><span className={`badge ${row.status==="healthy"?"badge-good":row.status==="failed"?"badge-bad":"badge-warn"}`}>{row.status.replaceAll("_"," ")}</span></td><td className="data-font text-[11px]">{row.latest_data_at?new Date(row.latest_data_at).toLocaleString("en-PK"):"Unavailable"}</td><td className="data-font text-[11px]">{row.last_success?new Date(row.last_success).toLocaleString("en-PK"):"Never"}</td><td className="data-font text-[11px]">{row.accepted} accepted · {row.updated} updated · {row.rejected} rejected</td><td className="max-w-72 text-[11px] text-muted">{row.error??(row.status==="never_run"?"Provider has not run.":row.status==="stale"?"No sufficiently fresh observed data.":"—")}</td></tr>)}</tbody></table></div>:<div className="notice notice-warn m-4"><Icon name="warning"/><span>Source-level health could not be loaded. Market values above retain their existing freshness labels.</span></div>}</details>
    <div className="metric-strip mt-4 grid-cols-3"><Metric label="Market breadth" value={`${adv} / ${dec}`} note="Advancers / decliners"/><Metric label="Total volume" value={snap?num(snap.total_volume,0):"—"}/><Metric label="Total value" value={snap?`PKR ${num(snap.total_value)}`:"—"}/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><section className="panel"><div className="panel-head"><h2 className="panel-title">Sector leadership</h2><span className="text-[11px] text-muted">Average daily change</span></div><div className="panel-body space-y-3">{sectors.slice().sort((a,b)=>Number(b.average_change_percent)-Number(a.average_change_percent)).map(s=><div key={s.sector} className="grid grid-cols-[1fr_2fr_62px] items-center gap-3"><span className="truncate text-[12px] font-semibold">{s.sector}</span><div className="h-2 overflow-hidden rounded-full bg-surface"><div className={`h-full rounded-full ${Number(s.average_change_percent)>=0?"bg-accent":"bg-warn"}`} style={{width:`${Math.min(100,Math.abs(Number(s.average_change_percent))*25)}%`}}/></div><span className={`data-font text-right text-[11px] ${tone(s.average_change_percent)}`}>{pct(s.average_change_percent)}</span></div>)}</div></section><section className="panel"><div className="panel-head"><h2 className="panel-title">Breadth by sector</h2></div><div className="table-wrap"><table className="data-table !min-w-0"><thead><tr><th>Sector</th><th>Adv</th><th>Dec</th><th>Unch</th></tr></thead><tbody>{sectors.slice(0,8).map(s=><tr key={s.sector}><td className="max-w-40 truncate font-semibold">{s.sector}</td><td className="positive">{s.advancers}</td><td className="negative">{s.decliners}</td><td>{s.unchanged}</td></tr>)}</tbody></table></div></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><Mover title="Top gainers" rows={overview?.top_gainers??[]}/><Mover title="Top losers" rows={overview?.top_losers??[]}/><Mover title="Volume leaders" rows={overview?.top_volume??[]} volume/></div>
    <section className="panel mt-4"><div className="panel-head"><div><h2 className="panel-title">Macro and market regime</h2><p className="mt-1 text-[11px] text-muted">{regime?.method_note??"Structured macro observations are unavailable."}</p></div><span className={`badge ${regime?.regime==="risk_off"?"badge-bad":regime?.regime==="not_evaluated"?"badge-warn":"badge-good"}`}>{regime?.regime?.replaceAll("_"," ")??"Not evaluated"}</span></div>{regime&&Object.keys(regime.dimensions).length?<><div className="grid gap-px bg-line md:grid-cols-3">{Object.entries(regime.dimensions).map(([key,value])=><div className="bg-white p-4" key={key}><p className="metric-label">{key.replaceAll("_"," ")}</p><p className="mt-2 text-sm font-semibold">{String(value.status??"not evaluated").replaceAll("_"," ")}</p><p className="mt-1 text-[11px] text-muted">{value.value!=null?`${num(value.value)} ${String(value.unit??"")} · prior ${num(value.previous_value)} · change ${Number(value.change)>0?"+":""}${num(value.change)}`:`${String(value.advancers??"—")} advancers vs ${String(value.decliners??"—")} decliners`}</p><p className="mt-1 text-[10px] text-muted">{String(value.series_name??value.trade_date??"Source series unavailable")}</p></div>)}</div><div className="border-t border-line bg-[#fafaf8] px-4 py-3 text-[11px] leading-5 text-muted"><strong className="text-ink">Exact rule:</strong> rising rates, rising PKR-per-USD, rising inflation and negative breadth are stress signals. Two or more means risk-off; zero with positive breadth means constructive; otherwise mixed. Rising oil routes an oil-spike scenario but is not itself counted as a risk-off vote.</div></>:<div className="p-4 text-xs text-muted">No sufficient structured macro or breadth history is available; the regime is not evaluated.</div>}</section>
    {showDirectory?<section className="panel mt-4"><div className="panel-head"><h2 className="panel-title">Company directory</h2><span className="text-[11px] text-muted">{directory.status==="error"?"Request failed":directory.status==="loading"?"Searching…":directory.query?`Results for "${directory.query}"`:`${directory.rows.length} results`}</span></div>{directory.status==="error"?<div className="notice notice-error m-4"><Icon name="warning"/><span>Company directory request failed: {directory.error}. Existing rows are not presented as a current search result.</span></div>:directory.status==="loading"?<div className="grid gap-px divide-y divide-line p-4 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3,4,5,6].map(i=><div className="skeleton h-14 w-full" key={i}/>)}</div>:directory.rows.length?<div className="grid divide-y divide-line sm:grid-cols-2 lg:grid-cols-3">{directory.rows.map(c=><Link className="flex items-center justify-between p-4 transition-colors hover:bg-[#f8f9f6]" key={c.symbol} href={`/companies/${c.symbol}`}><div><strong className="text-[13px] text-accent">{c.symbol}</strong><p className="mt-1 text-[11px]">{c.name}</p></div><span className="max-w-28 truncate text-[11px] text-muted">{c.sector}</span></Link>)}</div>:<div className="empty-state m-4"><strong>No companies found</strong><span>{directory.query?`No active company matches "${directory.query}".`:"No active companies are available."}</span></div>}</section>:null}
  </div>;
}

function Metric({label,value,note}:{label:string;value:string;note?:string}){return <div className="metric"><p className="metric-label">{label}</p><p className="metric-value data-font">{value}</p>{note?<p className="metric-note">{note}</p>:null}</div>}
function DataState({label,value}:{label:string;value:string}){return <div className="bg-white p-3"><dt className="metric-label">{label}</dt><dd className="mt-1 break-words font-semibold capitalize">{value}</dd></div>}
function Mover({title,rows,volume=false}:{title:string;rows:MarketPrice[];volume?:boolean}){return <section className="panel"><div className="panel-head"><h2 className="panel-title">{title}</h2></div><div className="divider-list">{rows.slice(0,6).map(r=><Link href={`/companies/${r.symbol}`} key={r.symbol} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 px-4 py-3 transition-colors hover:bg-[#f8f9f6]"><strong className="text-accent">{r.symbol}</strong><span className="data-font text-[11px]">{volume?num(r.volume,0):`PKR ${num(r.close)}`}</span><span className={`data-font text-[11px] font-semibold ${tone(r.change_percent)}`}>{pct(r.change_percent)}</span></Link>)}</div></section>}
