"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Icon } from "@/components/Icon";
import { Company, MarketFreshness, MarketOverview, MarketPrice, getCompanies, getMarketFreshness, getMarketOverview } from "@/lib/api";

const num=(v:unknown,d=2)=>new Intl.NumberFormat("en-PK",{maximumFractionDigits:d,notation:Number(v)>999999?"compact":"standard"}).format(Number(v||0));
const pct=(v:unknown)=>v==null?"—":`${Number(v)>0?"+":""}${Number(v).toFixed(2)}%`;
const tone=(v:unknown)=>Number(v)>0?"positive":Number(v)<0?"negative":"muted";

export default function MarketPage(){
  const [overview,setOverview]=useState<MarketOverview|null>(null);const [fresh,setFresh]=useState<MarketFreshness|null>(null);const [companies,setCompanies]=useState<Company[]>([]);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [showDirectory,setShowDirectory]=useState(true);
  useEffect(()=>{void Promise.all([getMarketOverview(),getMarketFreshness(),getCompanies()]).then(([o,f,c])=>{setOverview(o);setFresh(f);setCompanies(c)}).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))},[]);
  useEffect(()=>{const t=setTimeout(()=>void getCompanies(query).then(setCompanies).catch(()=>{}),250);return()=>clearTimeout(t)},[query]);
  if(loading)return <div className="page-wrap"><div className="panel h-96 skeleton"/></div>;
  if(error)return <div className="page-wrap"><div className="notice notice-error"><Icon name="warning"/>{error}</div></div>;
  const snap=overview?.snapshot;const sectors=overview?.sectors??[];const adv=sectors.reduce((a,s)=>a+s.advancers,0),dec=sectors.reduce((a,s)=>a+s.decliners,0);
  return <div className="page-wrap">
    <header className="page-heading"><div><p className="eyebrow">Pakistan Stock Exchange</p><h1 className="page-title">Market intelligence</h1><p className="page-subtitle">Benchmark status, breadth, sector leadership and liquidity from structured market observations.</p></div><div className="flex w-full flex-wrap gap-2 sm:w-auto"><button className="btn btn-secondary" onClick={()=>setShowDirectory(!showDirectory)}><Icon name="settings"/>{showDirectory?"Hide directory":"Show directory"}</button><label className="relative min-w-0 flex-1 sm:w-64"><span className="sr-only">Search companies</span><input className="field pl-9" placeholder="Search companies" value={query} onChange={e=>setQuery(e.target.value)}/><Icon name="search" className="absolute left-3 top-3 text-muted"/></label></div></header>
    {fresh?.stale_warning?<div className="notice notice-warn mb-4"><Icon name="clock"/><span>{fresh.stale_warning}</span></div>:null}
    <div className="source-rail flex flex-wrap items-end justify-between gap-5 px-6 py-5"><div><div className="flex items-center gap-2"><span className={`badge ${fresh?.is_stale?"badge-warn":"badge-good"}`}>{fresh?.is_stale?"Stale data":"Current data"}</span><span className="text-[11px] text-muted">{fresh?.latest_trade_date??"Trade date unavailable"}</span></div><p className="mt-4 text-[15px] font-semibold">{snap?.index_name??"Market index unavailable"}</p><p className="mt-1 text-[11px] text-muted">{fresh?.latest_used_provider??fresh?.latest_source??"Source unavailable"}</p></div><div className="sm:text-right"><p className="data-font text-[36px] font-semibold leading-none tracking-[-.045em]">{snap?num(snap.index_value):"—"}</p><p className={`data-font mt-2 text-[15px] font-semibold ${tone(snap?.index_change_percent)}`}>{pct(snap?.index_change_percent)}</p></div></div>
    <div className="metric-strip mt-4 grid-cols-3"><Metric label="Market breadth" value={`${adv} / ${dec}`} note="Advancers / decliners"/><Metric label="Total volume" value={snap?num(snap.total_volume,0):"—"}/><Metric label="Total value" value={snap?`PKR ${num(snap.total_value)}`:"—"}/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><section className="panel"><div className="panel-head"><h2 className="panel-title">Sector leadership</h2><span className="text-[11px] text-muted">Average daily change</span></div><div className="panel-body space-y-3">{sectors.slice().sort((a,b)=>Number(b.average_change_percent)-Number(a.average_change_percent)).map(s=><div key={s.sector} className="grid grid-cols-[1fr_2fr_62px] items-center gap-3"><span className="truncate text-[12px] font-semibold">{s.sector}</span><div className="h-2 overflow-hidden rounded-full bg-surface"><div className={`h-full rounded-full ${Number(s.average_change_percent)>=0?"bg-accent":"bg-warn"}`} style={{width:`${Math.min(100,Math.abs(Number(s.average_change_percent))*25)}%`}}/></div><span className={`data-font text-right text-[11px] ${tone(s.average_change_percent)}`}>{pct(s.average_change_percent)}</span></div>)}</div></section><section className="panel"><div className="panel-head"><h2 className="panel-title">Breadth by sector</h2></div><div className="table-wrap"><table className="data-table !min-w-0"><thead><tr><th>Sector</th><th>Adv</th><th>Dec</th><th>Unch</th></tr></thead><tbody>{sectors.slice(0,8).map(s=><tr key={s.sector}><td className="max-w-40 truncate font-semibold">{s.sector}</td><td className="positive">{s.advancers}</td><td className="negative">{s.decliners}</td><td>{s.unchanged}</td></tr>)}</tbody></table></div></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><Mover title="Top gainers" rows={overview?.top_gainers??[]}/><Mover title="Top losers" rows={overview?.top_losers??[]}/><Mover title="Volume leaders" rows={overview?.top_volume??[]} volume/></div>
    <div className="mt-4 grid gap-4 md:grid-cols-2"><section className="rounded-xl bg-surface p-4"><h2 className="text-[13px] font-semibold">Macro context</h2><p className="mt-1 text-[11px] text-muted">The market API does not expose a structured macro snapshot.</p></section><section className="rounded-xl bg-surface p-4"><h2 className="text-[13px] font-semibold">Important events</h2><p className="mt-1 text-[11px] text-muted">No structured market events were returned.</p></section></div>
    {showDirectory?<section className="panel mt-4"><div className="panel-head"><h2 className="panel-title">Company directory</h2><span className="text-[11px] text-muted">{companies.length} results</span></div><div className="grid divide-y divide-line sm:grid-cols-2 lg:grid-cols-3">{companies.map(c=><Link className="flex items-center justify-between p-4 transition-colors hover:bg-[#f8f9f6]" key={c.symbol} href={`/companies/${c.symbol}`}><div><strong className="text-[13px] text-accent">{c.symbol}</strong><p className="mt-1 text-[11px]">{c.name}</p></div><span className="max-w-28 truncate text-[11px] text-muted">{c.sector}</span></Link>)}</div></section>:null}
  </div>;
}

function Metric({label,value,note}:{label:string;value:string;note?:string}){return <div className="metric"><p className="metric-label">{label}</p><p className="metric-value data-font">{value}</p>{note?<p className="metric-note">{note}</p>:null}</div>}
function Mover({title,rows,volume=false}:{title:string;rows:MarketPrice[];volume?:boolean}){return <section className="panel"><div className="panel-head"><h2 className="panel-title">{title}</h2></div><div className="divider-list">{rows.slice(0,6).map(r=><Link href={`/companies/${r.symbol}`} key={r.symbol} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 px-4 py-3 transition-colors hover:bg-[#f8f9f6]"><strong className="text-accent">{r.symbol}</strong><span className="data-font text-[11px]">{volume?num(r.volume,0):`PKR ${num(r.close)}`}</span><span className={`data-font text-[11px] font-semibold ${tone(r.change_percent)}`}>{pct(r.change_percent)}</span></Link>)}</div></section>}
